hibernate/hibernate-reactive

hibernate-rx-api/build.gradle, hibernate-rx-api/src/test/java/org/hibernate/rx/MockRxSession.java, hibernate-rx-api/src/test/java/org/hibernate/rx/RxSessionApiTest.java, hibernate-rx-core/build.gradle
Initial experiments testing with Junit5 + Vert.x Junit5
=> Reactive testing using Junit 5 and Vert.x Junit5

.github/workflows/build.yml, README.md, gradle/wrapper/gradle-wrapper.properties, hibernate-rx-core/build.gradle, hibernate-rx-core/src/test/java/org/hibernate/rx/BaseRxTest.java, hibernate-rx-core/src/test/java/org/hibernate/rx/MySQLAutoincrementTest.java, hibernate-rx-core/src/test/java/org/hibernate/rx/MySQLBasicTest.java, hibernate-rx-core/src/test/java/org/hibernate/rx/containers/MySQLDatabase.java, hibernate-rx-core/src/test/java/org/hibernate/rx/containers/PostgreSQLDatabase.java, hibernate-rx-core/src/test/resources/log4j.properties
=> Create CI pipeline and add Testcontainers

hibernate-rx-core/src/main/java/org/hibernate/rx/event/impl/DefaultRxLoadEventListener.java, hibernate-rx-core/src/main/java/org/hibernate/rx/event/impl/DefaultRxRefreshEventListener.java, hibernate-rx-core/src/main/java/org/hibernate/rx/persister/entity/impl/RxEntityPersister.java, hibernate-rx-core/src/main/java/org/hibernate/rx/persister/entity/impl/RxJoinedSubclassEntityPersister.java, hibernate-rx-core/src/main/java/org/hibernate/rx/persister/entity/impl/RxSingleTableEntityPersister.java, hibernate-rx-core/src/main/java/org/hibernate/rx/persister/entity/impl/RxUnionSubclassEntityPersister.java
Re-do of #88 due to conflicts.
=> Cleanup DefaultRxLoadEventListener 

hibernate-rx-core/src/test/java/org/hibernate/rx/configuration/RxConnectionPoolTest.java, hibernate-rx-core/src/test/java/org/hibernate/rx/containers/DatabaseConfiguration.java
Follows https://github.com/hibernate/hibernate-reactive/pull/110
@aguibert Could you have look at this PR and let me know if it makes sense to you?
It's just a bit of refactoring but I would like to double check that I didn't miss anything.
Thanks
=> Follow up of Vert.x Pool configuration

build.gradle
We can merge it as soon as the release has finished
=> #121 Upgrade to ORM 5.4.16.Final

.github/workflows/build.yml, README.md, build.gradle, hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/service/ReactiveConnectionPoolProviderImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/service/initiator/DialectFromUrlJdbcEnvironmentInitiator.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/DB2BasicTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/VertxMySqlContainer.java, hibernate-reactive-core/src/test/resources/vertx-default-jul-logging.properties, hibernate-rx-core/src/test/java/org/hibernate/rx/DB2BasicTest.java, hibernate-rx-core/src/test/java/org/hibernate/rx/containers/DB2Database.java, hibernate-rx-core/src/test/java/org/hibernate/rx/containers/VertxMySqlContainer.java, hibernate-rx-core/src/test/resources/vertx-default-jul-logging.properties, publish.gradle
=> Support for DB2

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
=> Upgrade from Postgres 9.6 to 12

hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/impl/SqlClientConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/service/ReactiveConnectionPoolProviderImpl.java
=> Refactor to not depend on any specific Vertx drivers

README.md, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactivePersistenceContextAdapter.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEntityEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveOuterJoinLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveBatchingCollectionInitializerBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveCollectionInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveCollectionLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveDynamicBatchingCollectionInitializerBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactivePaddedBatchingCollectionInitializerBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveSubselectOneToManyLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveAbstractEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveBatchingEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveDynamicBatchingEntityLoaderBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePaddedBatchingEntityLoaderBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveUniqueEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/hql/impl/ReactiveQueryLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchFetchTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/SubselectFetchTest.java
=> batch and subselect fetching

README.md, hibernate-reactive-core/src/main/java/org/hibernate/reactive/boot/impl/ReactiveServiceRegistryInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/ReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/IdentifierGeneration.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveGeneratorWrapper.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveIdentifierGeneratorFactory.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveIdentifierGeneratorFactoryInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/SequenceReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/TableReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveOneToManyJoinWalker.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveCascadeEntityJoinWalker.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveDynamicBatchingEntityLoaderBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveEntityJoinWalker.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/impl/Delete.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/impl/Insert.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/impl/Parameters.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/impl/Update.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CustomGeneratorTest.java
=> custom id generators

README.md, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactivePersistenceContextAdapter.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/CachingReactiveLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveOuterJoinLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/custom/impl/ReactiveCustomLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveAbstractEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveBatchingEntityLoaderBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePlanEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/hql/impl/ReactiveQueryLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyManyToOneAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyOneToManyAssociationWithFetchTest.java
This fixes #183.
It was rather a lot of work, and perhaps hardly worth it, but at least it forced me to sort out some stuff in the `Loader` hierarchy.
=> support for EntityGraph and @NamedEntityGraph

example/src/main/java/org/hibernate/example/reactive/Main.java, example/src/main/java/org/hibernate/example/reactive/MutinyMain.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/Criteria.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/CriteriaQueryOptions.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaBuilderImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaDeleteImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaUpdateImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java
=> support for criteria update + delete

hibernate-reactive-core/src/test/java/org/hibernate/reactive/AutoincrementTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseMutinyTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BasicTypesAndCallbacksTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CascadeTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompositeIdTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
Hibernate Reactive can do all these things better.
=> get rid of unnecessary direct use of ReactiveConnection from test suite

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveBatchingCollectionInitializerBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveDynamicBatchingCollectionDelegator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveDynamicBatchingCollectionInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveDynamicBatchingCollectionInitializerBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactivePaddedBatchingCollectionInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactivePaddedBatchingCollectionInitializerBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveBatchingEntityLoaderBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveDynamicBatchingEntityDelegator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveDynamicBatchingEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveDynamicBatchingEntityLoaderBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePaddedBatchingEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePaddedBatchingEntityLoaderBuilder.java
A bit of cleanup for #188. I didn't really clean up any code but just breaking out all the inner classes and adding documentation helps quite a lot.
=> try to make the batch loaders stuff comprehensible

README.md, example/src/main/java/org/hibernate/example/reactive/Main.java, example/src/main/java/org/hibernate/example/reactive/MutinyMain.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
This helps make trivial examples look nicer,
=> add convenience withTransaction() method to SessionFactory

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactivePersistenceContextAdapter.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java
=> snapshot fetching

README.md, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompositeIdTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
By closing the session properly once in a while.
=> let's set a good example in tests

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/CachingReactiveLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/custom/impl/ReactiveCustomLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/hql/impl/ReactiveQueryLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaQueryImpl.java
This pull includes all the planned changes that were waiting on a new release of Hibernate (mainly code deletion).
=> Fallout from Hibernate core upgrade

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveCollectionLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveOneToManyJoinWalker.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/impl/Parameters.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/FilterTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/package-info.java
This is for #211.
It's *mostly* working, except that filter parameters + collection fetching is currently broken. (I have fixed the SQL generation, but the parameter values don't get bound.)
=> fixes and tests for filter parameters

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveHQLQueryPlan.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeSQLQueryPlan.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryTranslatorImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java
This patch allows you to execute native SQL DML statements via the `Session`.
=> add support for native SQL update, insert, and delete

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
For @FroMage and Panache.
See #217.
=> add setHint() and overloaded setLockMode() to Query

README.md, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java
=> add properties for configging the Vert.x pool

README.md, example/build.gradle, example/src/main/java/org/hibernate/example/reactive/Book.java, example/src/main/java/org/hibernate/example/reactive/Main.java, example/src/main/resources/META-INF/persistence.xml, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyPropertyTest.java
So this here's my implementation of #204.
WDYT?
=> lazy property fetching via session.fetch()

.github/workflows/build.yml, example/build.gradle, example/src/main/java/org/hibernate/example/reactive/Main.java, example/src/main/java/org/hibernate/example/reactive/MutinyMain.java, example/src/main/resources/META-INF/persistence.xml
Issue https://github.com/hibernate/hibernate-reactive/issues/253
Run the examples on MySQL and PostgreSQL.
=> #253 Smoke test examples

build.gradle
=> Upgrade to Hibernate ORM 5.4.18.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveInitializeCollectionEventListener.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/FetchModeSubselectEagerTest.java
https://github.com/hibernate/hibernate-reactive/issues/261
=> 261 subselet fetching

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/ReactiveExceptionConverter.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseMutinyTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinyExceptionsTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/StageExceptionsTest.java
=> [#281] Return PersistenceException when constraint violation occurs

hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyInitializationExceptionWithMutiny.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyInitializationExceptionWithStage.java
https://github.com/hibernate/hibernate-reactive/issues/282
=> [#282] Throw LazyInitializationException

hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesAndCallbacksForAllDBsTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesForSelectedDBTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BigDecimalAsString.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/Json.java
=> add test for UserType mappings

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java
I made a mistake and thought that this only made sense for DML.
@DavideD set me straight, see #284
=> allow createNativeQuery(String) to be used with SQL selects

documentation/src/main/asciidoc/reference/getting-started.adoc, documentation/src/main/asciidoc/reference/index.adoc, documentation/src/main/asciidoc/reference/introduction.adoc, documentation/src/main/asciidoc/reference/preface.adoc
=> first stab at reference documentation

hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesAndCallbacksForAllDBsTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesForSelectedDBTest.java
=> enable some tests for DB2 after Vert.x update

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityIdentityInsertAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityRegularInsertAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityUpdateAction.java
=> throw exception for @Generated properties

README.md, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoaderBasedResultSetProcessor.java
Fixes #309.
See https://github.com/hibernate/hibernate-orm/pull/3484.
=> Fix breakage due to changes to core

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java
=> much better implementation of ProxyConnection

README.md, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/IdentifierGeneration.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/SequenceReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/TableReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveGenerationTarget.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BlockSequenceGeneratorTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BlockTableGeneratorTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/SequenceGeneratorTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/TableGeneratorTest.java
=> block (hi/lo) id generation

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/QueryParametersAdaptor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/FilterTest.java
=> fix filter parameter binding in collection fetching

README.md, build.gradle
I haven't tested it locally: entrusting CI to test on all DBs.
=> Upgrade to Hibernate ORM 5.4.21.Final

documentation/src/main/asciidoc/reference/introduction.adoc, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPoolConfiguration.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPoolConfigurationInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/Settings.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/ReactiveConnectionPoolTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/testing/TestingRegistryRule.java
Allow the user to micromanage the pool configuration via a plug-in service.
Solves use cases like #304.
=> introduce SqlClientPoolConfiguration

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java
=> support native-style connection URIs

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CascadingActions.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
=> add overloaded lock(),refresh(),find() taking LockOptions

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLockEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveRefreshEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReferenceTest.java
automatically fetch them at the start of event processing
fixes #359
=> allow proxies to be passed to remove(), lock(), refresh()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ObjectType.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionFactoryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java
An elegant solution requires:
<https://github.com/eclipse-vertx/vertx-sql-client/issues/657>
And we can remove this workaround once it is there.
=> temporary workaround solution to #336

README.md, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ObjectType.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionFactoryImpl.java
=> upgrade to Vert.x 3.9.3

example/src/main/java/org/hibernate/example/reactive/MutinyMain.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java
=> make Mutiny.Session more friendly for method refs

README.md, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/testing/CachedQueryResultsTest.java
=> add methods for query caching to Query

example/src/main/java/org/hibernate/example/reactive/Main.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactivePersistenceContextAdapter.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/SessionUtil.java
I feel like this must be a bug in Hibernate ORM that I'm dealing with here.
See discussion in #374.
=> workaround for collections in field-level lazy fetching

documentation/src/main/asciidoc/reference/introduction.adoc, example/src/main/java/org/hibernate/example/reactive/Author.java, example/src/main/java/org/hibernate/example/reactive/Book.java, example/src/main/java/org/hibernate/example/reactive/Main.java, example/src/main/java/org/hibernate/example/reactive/MutinyMain.java
So use them in the example program.
Fixes #382.
=> getters and setters are required except in Quarkus

hibernate-reactive-core/src/test/java/org/hibernate/reactive/CachedQueryResultsTest.java
to CachedQueryResultsTest
I think it was in the wrong package
=> Move CachedQueryResultsTest from  org.hibernate.reactive.testing package

README.md, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoaderBasedResultSetProcessor.java
- https://github.com/hibernate/hibernate-orm/commit/8b52c403db79f8bcfaf0844fd5e7d14a717fbb38
=> Upgrade to Hibernate ORM 5.4.22.Final

documentation/src/main/asciidoc/reference/introduction.adoc, hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/FindAfterFlushTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyInitializationExceptionWithMutiny.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySequenceGeneratorTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java
=> update to Mutiny 0.9.0

documentation/src/main/asciidoc/reference/introduction.adoc, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ExternalSqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java
=> cleanups after #395

documentation/src/main/asciidoc/reference/introduction.adoc
=> use Mutiny in docs

README.md
The integration with Quarkus has now been released.
=> [#405] Update README about Quarkus integration

README.md, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
=> Upgrade to Vert.x 3.9.4

.github/workflows/build.yml, build.gradle, documentation/build.gradle, gradle.properties, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesAndCallbacksForAllDBsTest.java
Built on top of https://github.com/hibernate/hibernate-reactive/pull/429
=> Fix test failure on JDK 15+

documentation/build.gradle, documentation/src/main/javadoc/overview.html
=> add overview page to JavaDoc

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java
Proposed `Query.getSingleResultOrNull()` method.
=> fix doc for getSingleResult() and add getSingleResultOrNull()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java
=> better error message for unknown URI scheme

.github/workflows/build.yml, README.md, build.gradle, documentation/build.gradle, documentation/src/main/javadoc/overview.html, example/src/main/java/org/hibernate/example/reactive/MutinyMain.java, gradle/version.properties, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveActionQueue.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java, release/build.gradle
Changes that are in master but we haven't included in the vert.x 4 branch
=> Vert.x 4 updates

.github/workflows/build.yml, release/build.gradle
=> [#472] Fix authorization to publish the docs

README.md, build.gradle
changes: https://hibernate.atlassian.net/issues/?jql=project%20%3D%2010031%20AND%20fixVersion%20%3D%2031910%20ORDER%20BY%20priority%20DESC%2C%20key%20ASC
=> Upgrade to Hibernate ORM 5.4.27.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerManyToOneAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyManyToOneAssociationTest.java
=> Handle null many-to-one associations

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/IdentifierGeneration.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/IdentifierGenerationTypeTest.java
Follows https://github.com/hibernate/hibernate-reactive/pull/524
Add some tests on top of the orginal commit
Fixes #526
=> [#526] Don't throw exception when id is Short 

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/StandAloneReactiveTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/JdbcUrlParserTest.java
=> Service lookup for ReactiveConnectionPool to happen once only

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
I forgot to add these when I did #493
fixes #520
=> add calls to factory.uni() from Query and StatelessSession

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java
=> fix idle timeout

hibernate-reactive-core/src/main/java/org/hibernate/reactive/bulk/impl/ReactiveBulkIdStrategy.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/TableReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveCollectionLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/custom/impl/ReactiveCustomLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveAbstractEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveDynamicBatchingEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePlanEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/hql/impl/ReactiveQueryLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ExternalSafeSqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ExternalSqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/Parameters.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeSQLQueryPlan.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryTranslatorImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchQueryOnConnectionTest.java
Follows the conversation we had here: #508
It doesn't seem too bad but I'm not sure I've covered all the use cases. It might be a way to see which test we still miss.
=> [#508] Process SQL string during generation

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePlanEntityLoader.java
It should return true when there are filters
=> [#508] Fix ReactivePlanEntityLoader#hasFilters

build.gradle
I will wait for CI to finish the checks but it seems that updating testcontainers was enough
=> [#543] CI failing because of Docker image not found

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveProviderChecker.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJtaPlatformInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveMarkerServiceInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveMarkerServiceSingleton.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactivePersisterClassResolver.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactivePersisterClassResolverInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveQueryTranslatorFactory.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveQueryTranslatorFactoryInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSessionFactoryBuilderInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSessionFactoryBuilderService.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryTranslatorImpl.java
I've added the javadoc to the classes in org.hibernate.reactive.provider.
=> [#398] Update javadoc

README.md, build.gradle
Follows: https://github.com/hibernate/hibernate-reactive/pull/553
=> Update to ORM 5.4.28.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveActionQueue.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/Cascade.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveOrphanRemovalAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveResultSetProcessor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrphanRemovalTest.java
Probably needs more tests.
Fixes  #506
=> orphan removal

README.md, hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/bulk/impl/ReactiveIdTableSupport.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerManyToOneAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOneToManyAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOneToOneAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyManyToOneAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyOneToManyAssociationWithFetchTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReferenceTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UriConfigTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DatabaseConfiguration.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/VertxMariaContainer.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/testing/DatabaseSelectionRuleTests.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesForSelectedDBTest.java
=> Maria DB support

.github/workflows/build.yml, .github/workflows/tracking-orm-5.build.yml, .github/workflows/tracking-vertx-3.build.yml, hibernate-reactive-core/build.gradle, podman.md
=> [#471] Add MariaDB to workflows, podman.md and build.gradle

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
=> Fix typo in javadocs: contianer

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForEmbeddedEmbeddableTest.java
Added tests for embeddable inside an `@Embeddable`
```
@Embeddable
public static class Phone {
...
@ElementCollection
private List<AlternativePhone> alternatives = new ArrayList<>();
}
@Embeddable
public static class AlternativePhone {
...
}
```
=> [#533] added tests for collection of embeddables inside an `@Embeddable`

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeSetTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForEmbeddableTypeListTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOrderedElementCollectionForEmbeddableTypeListTest.java
=> tests for list ordering

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java
1. fix some generics-related warnings
2. `afterRowInsert()` would need to be called in `compose()` but it's not implemented yet anyway
3. suck the ugly `AtomicInteger` into the util method
4. use static imports
=> minor cleanups to ReactiveBasicCollectionPersister

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeMapTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForEmbeddableEntityTypeMapTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForEmbeddedEmbeddableMapTest.java
=> support for Map<> `@ElementCollection`

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/Cascade.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveCollectionUpdateAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityVerifyVersionProcess.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEntityEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveInitializeCollectionEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLockEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactivePersistEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveRefreshEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveCollectionLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveDynamicBatchingCollectionInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveSubselectOneToManyLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveAbstractEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveBatchingEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java
Folks, I left the call to `afterRowInsert()` as a TODO *intentionally*. Please read the Javadoc of what that method is supposed to do.
=> use static imports + remove inoperative code

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveInitializeCollectionEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveBasicCollectionLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveBatchingCollectionInitializerBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveOneToManyLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveSubselectCollectionLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveSubselectOneToManyLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyOrderedElementCollectionForEmbeddableTypeListTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/SubselectElementCollectionForEmbeddableTypeListTest.java
also added some Javadoc
fixes #551
=> lazy initialization for @ElementCollection

README.md, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ManyToManyTest.java
`@ManyToMany` associations seem to be working now. (After implementing support for `@ElementCollection`.)
We probably want to add some additional tests at some stage, but since we've pretty exhaustively tested `@ElementCollection` already, I'm feeling pretty confident that this works.
Fixes #45.
=> test for @ManyToMany

README.md, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveAbstractCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ManyToManyMapTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ManyToManySetTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToManyMapTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToManySetTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToManyTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrderedEmbeddableCollectionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrderedManyToManyTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrderedOneToManyTest.java
Fixes #589 and #581.
Supersedes #590.
=> unidirectional @OneToMany and @OrderColumn

hibernate-reactive-core/build.gradle
=> update to Mutiny 0.14.0

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveAbstractCollectionPersister.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrderedEmbeddableCollectionTest.java
Fixes [#602](https://github.com/hibernate/hibernate-reactive/issues/602)
related to PR's [#582 ](https://github.com/hibernate/hibernate-reactive/pull/582)& [#591](https://github.com/hibernate/hibernate-reactive/pull/591)
=> minor fix & test for multiple removes from ordered element collection

hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
and generally clean up unfinished code
=> enable autoflushing for native queries

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/SequenceReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/TableReactiveIdentifierGenerator.java
Don't issue concurrent requests for new hi values.
see #411
@Sanne @cescoffier  does this look right to you guys?
=> improving hi/lo id generation

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/AffectedEntities.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessSessionTest.java
Here's a proposed solution to #441.
Not sure how I feel about it.
WDYT?
=> overload createNativeQuery() to accept query spaces

README.md, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/Settings.java
=> upgrade to Vert.x 3.9.6 

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveResultSetProcessor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQueryExecutor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOneToManyAssociationTest.java
=> implement StatelessSession.internalLoad()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
I guess I just forgot about StatelessSession when I made this change to `Session` in #347.
=> make void-like methods of StatelessSession return Uni<Void>

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
=> add StatelessSession.withTransaction()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
=> add variadic methods StatelessSession

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/Criteria.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQueryExecutor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaDeleteImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaUpdateImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessSessionTest.java
=> add criteria queries to StatelessSession

.github/workflows/build.yml, .github/workflows/tracking-orm-5.build.yml, .github/workflows/tracking-vertx-3.build.yml
Testing the build with the stateless examples
=> Add Stateless example to the workflow

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/SequenceReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/TableReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/BatchingConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ProxyConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
And add a comment about batching, to make its semantics clear.
=> rename selectLong() to selectIdentifier()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
This approach maintains "statelessness" of the SS by using two of them!
=> alternative impl of StatelessSession batching

hibernate-reactive-core/src/test/java/org/hibernate/reactive/CustomStoredProcedureSqlTest.java
@blafond 
I've changed a bit your PR:
* Fixed the name of the test class
* Reformatted the code
* Removed the `@NamedStoreProcedure`, it's not needed for these tests (I think)
Can you merge this if you agree with the changes?
Thanks
=> Added tests for @SqlInsert, @SqlUpdate, and @SqlDelete containing stored procedures  

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveResultSetProcessor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/ReactiveUniqueEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveAbstractEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveBatchingEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePlanEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerUniqueKeyTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyUniqueKeyTest.java, publish.gradle
Fixes #565, but depends on https://github.com/hibernate/hibernate-orm/pull/3733.
=> support for non-primary key associations

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/Identifier.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/ReactiveResolveNaturalIdEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveResolveNaturalIdEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveIntegrator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/NaturalIdTest.java
I need to do some more thinking about this because `@SafeVarargs` doesn't work on interfaces so we get the stupid stupid useless fucking unchecked array creation warning. Dumbest thing in Java.
=> initial support for @NaturalIds

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmptyCompositeCollectionKeyTest.java
Fixes [#552](https://github.com/hibernate/hibernate-reactive/issues/552) and verifies expected behavior
=> Test property about mapping of null Embeddables

examples/native-sql-example/build.gradle, examples/native-sql-example/src/main/java/org/hibernate/reactive/example/nativesql/Author.java, examples/native-sql-example/src/main/java/org/hibernate/reactive/example/nativesql/Book.java, examples/native-sql-example/src/main/java/org/hibernate/reactive/example/nativesql/Main.java, examples/native-sql-example/src/main/java/org/hibernate/reactive/example/nativesql/MutinyMain.java, examples/native-sql-example/src/main/resources/META-INF/persistence.xml, examples/session-example/build.gradle, examples/session-example/src/main/java/org/hibernate/reactive/example/session/Author.java, examples/session-example/src/main/java/org/hibernate/reactive/example/session/Book.java, examples/session-example/src/main/java/org/hibernate/reactive/example/session/Main.java, examples/session-example/src/main/java/org/hibernate/reactive/example/session/MutinyMain.java, examples/session-example/src/main/resources/META-INF/persistence.xml
To `org.hibernate.reactive.example.*`
=> [#651] Rename examples packages

hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongCredentialsTest.java
enables testing during CI build of wrong credentials for non-PostgresSQL DB's to verify if the exception still exists or not for [#511](https://github.com/hibernate/hibernate-reactive/issues/511)
=> Removed rule to test only PostgresSQL

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerTest.java
It seems it works now, probably because issue #39 about
eager fetch select.
=> Enable testEagerParentFetchQuery

hibernate-reactive-core/build.gradle
Fixes [#661](https://github.com/hibernate/hibernate-reactive/issues/661)
=> Upgraded to JUnit 5

hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyOneToOneWithJoinColumnTest.java
From the conversation on Zulip
=> Test for lazy OneToOne associations

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/PreparedStatementAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UTCTest.java
I *think* this timezone handling is non-ridiculous.
=> proposed support for hibernate.jdbc.time_zone

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
Hrm. I'm not positive, but after re-reading the Javadoc, I'm wondering if this is a more correct implementation of `ResultSet.getTimestamp()`?
=> possibly more correct implementation of hibernate.jdbc.time_zone support

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, podman.md
=> [#690] Upgrade Db2 to version 11.5.5.1

dco.txt
Fixes #699 
@Sanne, could you check if this is the right file, please? Thanks
=> [#699] Add Developer Certificate of Origin

.github/workflows/build.yml, build.gradle, documentation/build.gradle, publish.gradle
=> [#687] Release via OSSRH

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/Cascade.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyReplaceOrphanedEntityTest.java
Fixes [#702](https://github.com/hibernate/hibernate-reactive/issues/702)
=> Adds removal of orphaned entities

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ProxyConnection.java
- Add better error message if it has been closed
- Don't explicity throw the exception, return a failed CS instead
=> Improve ProxyConnection error handling

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/Cascade.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToOneLazyOrphanRemovalTest.java
=> [#709]  Fix orphan removal when setting association to null

build.gradle
Fixes [#692](https://github.com/hibernate/hibernate-reactive/issues/692)
=> [#692] Upgraded spotless plugin to com.diffplug.spotless version 5.12.2

hibernate-reactive-core/build.gradle
Fixes [#705](https://github.com/hibernate/hibernate-reactive/issues/705)
=>  Upgrade to JBoss Logging 3.4.1.Final

hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToOneMapsIdTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToOnePrimaryKeyJoinColumnTest.java
Fixes [#710](https://github.com/hibernate/hibernate-reactive/issues/710)
=> Tests for `@MapsId` and `@PrimaryKeyJoinColumn`

hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToOneMapsIdTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToOnePrimaryKeyJoinColumnTest.java
@blafond  Renaming the tables seems to fix the build. I don't know what's the problem with those names
Fixes #710
=> [#710] Rename tables used for tests

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java
Follow the pattern used in the entity persisters, which I guess also slightly improves performance.
=> fix #726 npe when logging enabled

.github/workflows/build.yml, .github/workflows/tracking-orm-5.build.yml, .github/workflows/tracking-vertx-4.build.yml, README.md, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, podman.md
=> [#729] Fix links in the README and [#733] Upgrade version of the db for testing

hibernate-reactive-core/src/main/java/org/hibernate/reactive/vertx/impl/DefaultVertxInstance.java
=> [#736] Closing of Vert.x instance should be waited on

build.gradle
=> [#718] Upgrade gradle-nexus.publish-plugin to 1.1.0

.github/workflows/tracking-orm-5.build.yml, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeSetTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOrderedElementCollectionForEmbeddableTypeListTest.java
This is a draft because we need to upgrade to the next ORM 5.4 release before we can merge it.
Fixes #646
=> Upgrade to 5.4.31.Final and fix compatibility with ORM 5.5

hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
Fixes #758
Basically, we were closing the connection but not the session :-/
=> Session#isOpen is not false after Session#close

hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantTest.java
=> fix test on cockroach

hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/testing/SessionFactoryManager.java
@gavinking I prefer this approach
=> Add SessionFactoryManager#isStarted

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveFlushingEventListener.java
This change might not be necessary but it at least *looks* cleaner.
WDYT, @DavideD?
=> call prepareCollectionFlushes() from thenAccept()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveBatchingEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveDynamicBatchingEntityDelegator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePaddedBatchingEntityLoader.java
Fixes #775
Any idea how to test this?
=> Infinite recursion calls

tooling/jbang/Example.java, tooling/jbang/SampleIssueTest.java
* Update javadocs
* Fix issue with MySQL Driver (on my machine)
* Make it simpler to select a database
=> [#721] Refactor JBang classes

documentation/src/main/asciidoc/reference/introduction.adoc, hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/Context.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContextInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/package-info.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/vertx/VertxInstance.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessSessionTest.java
=> threadbound sessions

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java
Fixes #780
If there are multiple drivers in the classpath,
we sometime select the wrong one.
We didn't notice before because it might not happen
if the drivers are discovered in the right order.
=> [#780] Fix driver discovery issue

build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEntityEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoaderBasedResultSetProcessor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveResultSetProcessor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePlanEntityLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
As soon as Hibenrate ORM 5.4.32.Final has been released,
Rebased of https://github.com/hibernate/hibernate-reactive/pull/789
=> Upgrade to ORM 5.4.32.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java
A small reminder to check Quarkus when we add new services
=> Add comment about updating services in Quarkus

README.md, build.gradle, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeListTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOneToOneAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmptyCompositeCollectionKeyTest.java, tooling/jbang/Example.java, tooling/jbang/SampleIssueTest.java
Fixes #799 
Fixes #697 
and (indirectly)
Fixes #673
=> Upgrade to Vert.x 4.1

README.md
https://how-to.vertx.io/hibernate-reactive-howto/
=> link to Vert.x howto

hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
See #465.
Apparently Mutiny *does* filter out the `CompletionException`s, which is *great*.
Is that right, @cescoffier?
=> test the exception type after a UK violation

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQueryExecutor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessSessionTest.java
=> add StatelessSession.createNamedQuery()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
Ugh, I accidentally pushed my last commit related to this work to the wrong remote, and it got lost!
=> missing commit

README.md, build.gradle, tooling/jbang/Example.java, tooling/jbang/SampleIssueTest.java
=> [#815] Upgrade to Vert.x 4.1.0.CR2

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
Follows #813 
Fixes #811 
Hopefully, this will look a bit better.
=> Close session in case of exception in 

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
I've played with some very minor performance improvements for this, and renamed the variables + added some comments as I found it confusing.
=> Clarifications for the contextual Sessions

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java
And get rid of two unnecessary private methods.
This is a followup to #819.
=> throw an exception if put() called with no Vert.x context

README.md, build.gradle
=> Upgrade to ORM 5.5.0.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantNoResolverTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantTest.java
=> 766 stateless multitenancy

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantNoResolverTest.java
Fixes [#807](https://github.com/hibernate/hibernate-reactive/issues/807)
=> added withStatelessTransaction() methods

README.md, hibernate-reactive-core/build.gradle
Fixes [#740](https://github.com/hibernate/hibernate-reactive/issues/740)
Included note in README.md
=> added parameter to enable/disable standard output streams

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/Cascade.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CascadingAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CascadingActions.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java
=> get rid of unnecessary thenAccept()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveCollectionUpdateAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityDeleteAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityUpdateAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactivePersistEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/CachingReactiveLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/custom/impl/ReactiveCustomLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/hql/impl/ReactiveQueryLoader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveQueryTranslatorFactory.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveHQLQueryPlan.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryTranslatorImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
Some of this is far from perfect, and not actually typesafe but it's an improvement at least.
=> clean up some generic type issues

.github/workflows/build.yml, .github/workflows/tracking-orm-5.build.yml, .github/workflows/tracking-vertx-4.build.yml
=> Show standard output stream on CI

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/PreparedStatementAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
=> use NullValue to bind null values

hibernate-reactive-core/src/test/java/org/hibernate/reactive/UriConfigTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java
We might need to check if it works for the JDBC Url
=> [MSSQL] Fix UriConfigTest

README.md
* Add link to zulip hibernate-reactive-dev stream
* Add missing logo to the widgets
* Change widget style to flat
* Link the Hibernate Team logo to the website
* More descriptive alt text for widgets
=> Update README.md widgets

hibernate-reactive-core/src/test/java/org/hibernate/reactive/TimestampTest.java
Sometimes it fails on CI. I think it happens because it's too fast
and the updated instant matches the created instant.
Just in case, I've added a message error that prints the two instants
in case of exception so that we can verify the hypothesis.
We also now compare the instants when the entity is created and check
that they are equals to the ms.
=> Refactor TimestampTest

README.md, build.gradle
=> Upgrade to ORM 5.5.2.Final

hibernate-reactive-core/build.gradle
=> Upgrade PostgreSQL JDBC driver to 4.2.22

hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesForSelectedDBTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/Json.java
Fixes [#863](https://github.com/hibernate/hibernate-reactive/issues/863)
=> Added type check to convert String to JsonObject

README.md, build.gradle
=> Upgrade to Hibernate ORM 5.5.3.Final

hibernate-reactive-core/build.gradle
=> [#879] Upgrade to Mutiny 0.18.0

hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultilineImportsTest.java, hibernate-reactive-core/src/test/resources/complexMultilineImports.sql
This seems to work fine already; doesn't work in Quarkus for some reason.
=> Introduce a new test to verify multi-line parsed import.sql scripts

build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/TenantDependentPool.java
Fixes #882 
It seems there has been a change in the Pool api
=> [#882] Upgrade to Vert.x 4.1.1

examples/native-sql-example/build.gradle, examples/session-example/build.gradle, hibernate-reactive-core/build.gradle
Any reason not to upgrade any of these?
=> upgrade various misc dependencies

hibernate-reactive-core/build.gradle
@DavideD is there any reason our Mutiny is so far behind?
=> upgrade Mutiny to 0.19.2

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, podman.md, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
Db2 to 11.5.6.0
MariaDB to 10.6.2
CockroachDB to 21.1.5
Postgres to 13.3 (where it was still 13.2)
=> Upgrade databases dependencies

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/InternalStateAssertions.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
What would you all think of this?
Untested as my local DBs are busy.
=> Enable sanity assertions by default

hibernate-reactive-core/src/test/java/org/hibernate/reactive/FilterWithPaginationTest.java
The issue has been solved in Vert.x 4.1.1
Fixes #560
=> [#560] Enable FilterPageTest for Db2

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade ORM and Vert.x

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveTypeContributor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JsonTypeTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/LobTypeTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/UserJsonTypeTest.java
=> add built-in support for Vert.x JsonObject as a type

README.md, build.gradle
=> [#908] Upgrade to Hibernate ORM 5.5.5.Final

documentation/src/main/asciidoc/reference/introduction.adoc
Let's try making this even more prominent.
=> add a gotcha

build.gradle
=> [#915] Upgrade to testcontainers 1.16.0

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java
=> native queries returning Tuple

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
Tests to support [#877](https://github.com/hibernate/hibernate-reactive/issues/877)
=> Tests to check for BatchingConnection if batch size > 1

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/Context.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/BaseKey.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/MultitenantKey.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
=> Efficiency improvements: improve overhead of ContextKey comparisons

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java
Follows up on https://github.com/eclipse-vertx/vert.x/pull/4073
=> Take advantage of the Vert.x Context API improvements

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/IdentityGeneratorDynamicInsertTest.java
=> @DynamicInsert now works with IDENTITY columns

hibernate-reactive-core/src/test/java/org/hibernate/reactive/OptimisticLockingTest.java
There's already one test for `@OptimisticLocking`, but this is a little more complete.
=> add a test for @OptimisticLocking and merge()

README.md, build.gradle, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultilineImportsTest.java
=> Upgrade to ORM 5.6.0.CR1

hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
=> Close the connection after the session

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/spi/Implementor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
=> Add Implementor#getUuid()

.github/workflows/tracking-vertx-4.build.yml, README.md, build.gradle, gradle.properties, gradle/version.properties, hibernate-reactive-core/src/test/java/org/hibernate/reactive/TenantDependentPool.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/ReactiveConnectionPoolTest.java, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
Fixes #1010 
This change means that the next Hibernate Reactive release is going to be 1.1
I'm going to create a maintainance branch for Hibernate Reactive 1.0
=> Vert.x 4.2

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/AbstractReactiveInformationSchemaBasedExtractorImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/SqlServerReactiveInformationExtractorImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DatabaseConfiguration.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/TestableDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/BasicTypesTestEntity.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/ColumnTypesMappingTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateCockroachDBTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateMariaDBTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateMySqlTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdatePostgreSqlTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateSqlServerTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaValidationTestBase.java
Fixes #1005 
I think this is now good to be merged.
@blafond Could you have a look at the changes I made to [your original PR](https://github.com/hibernate/hibernate-reactive/pull/1040) and merge it if they make sense (and the build doesn't fail)?
Thanks
=> Additional tests for schema update and validation

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
=> overload withTransaction() for convenience

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade to Vert.x 4.2.1

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x to 4.1.6

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/AbstractReactiveInformationSchemaBasedExtractorImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/SqlServerReactiveInformationExtractorImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DatabaseConfiguration.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/TestableDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/BasicTypesTestEntity.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/ColumnTypesMappingTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateCockroachDBTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateMariaDBTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateMySqlTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdatePostgreSqlTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateSqlServerTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateTestBase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaValidationTestBase.java
Fixes #1005
Merge into 1.0 branch
=> Additional tests for schema update and validation - 1.0 branch

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
See #1011 and https://github.com/hibernate/hibernate-reactive/pull/1041#issuecomment-961090882
=> Add withStatelessTransaction(Function)

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/BatchingConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ProxyConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
=> fix Session.setBatchSize()

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/BatchingConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ProxyConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQueryExecutor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java
@gavinking Could you check  you are using tabs for indentation next time, please?
=> Code formattation

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchingConnectionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BatchSizeTest.java
=> Add StatelessSession#setBatchSize

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
and leave a meaningful comment
=> remove some commented code

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
unnecessary since https://github.com/eclipse-vertx/vertx-sql-client/issues/639
=> cleanup some nasty reflective code

README.md, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/bulk/impl/ReactiveBulkIdStrategy.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveGeneratorWrapper.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveIdentifierGeneratorFactory.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveIdentityGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveImprovedExtractionContextImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSchemaManagementTool.java
=> [#1078] Upgrade to Hibernate ORM 5.6.2.Final

.github/workflows/build.yml, .github/workflows/tracking-orm-5.build.yml, .github/workflows/tracking-vertx-4.build.yml, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, podman.md
=> [#1082] Upgrade to PostgreSQL 14.1 for testing

hibernate-reactive-core/build.gradle
=> [#1084] Upgrade to log4j 2.16.0

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade to Vert.x 4.2.2

.github/workflows/build.yml
=> Fix build actions for main

.github/workflows/build.yml
Only build tags related to 1.0
=> Fix github actions for 1.0 branch

examples/native-sql-example/build.gradle, examples/session-example/build.gradle, hibernate-reactive-core/build.gradle
=> Upgrade to Log4j 2.17.0

README.md, build.gradle, gradle.properties, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantNoResolverTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantTest.java, hibernate-reactive-core/src/test/resources/multitenancy-test.sql, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade to Vert.x 4.2.3

hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java
=> use List.isEmpty()

examples/native-sql-example/build.gradle, examples/session-example/build.gradle, hibernate-reactive-core/build.gradle
=> Upgrade Log4j to 2.17.1

examples/native-sql-example/build.gradle, examples/session-example/build.gradle, hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/tuple/MutinyValueGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/tuple/StageValueGenerator.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CurrentUser.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/DynamicUpdateTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertyJoinedTableTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertySingleTableTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertyUnionSubclassesTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OptimisticLockingTest.java
=> Reactive value generation

.github/workflows/build.yml, .github/workflows/tracking-orm-5.build.yml, .github/workflows/tracking-vertx-4.build.yml
See https://github.com/hibernate/hibernate-orm/pull/4615
=> Limit concurrent Github Actions builds

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/Context.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/BaseKey.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/MultitenantKey.java
Because I really am this anal.
=> slightly improve some javadoc

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveIdentifierGeneratorFactory.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/SequenceGeneratorTest.java
=> fix hibernate.default_schema and hibernate.default_catalog

README.md, build.gradle
=> Upgrade Hibernate ORM to 5.6.4.Final

integration-tests/verticle-postgres-it/build.gradle, integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/Product.java, integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/ProductVerticle.java, integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/StartVerticle.java, integration-tests/verticle-postgres-it/src/main/resources/log4j2.properties, integration-tests/verticle-postgres-it/src/test/java/org/hibernate/reactive/it/LocalContextTest.java
* Add a main to make it easier to start the verticles for benchmarking with external tools
* Add thread name and id to log messages
* Improve javadoc and comments
=> Refactor and clean up integration test

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade to Vert.x 4.2.4

hibernate-reactive-core/src/test/java/org/hibernate/reactive/UnicodeCharsTest.java
Follows [#quarkus#19539](https://github.com/quarkusio/quarkus/issues/19539)
=> Testing unicode chars

build.gradle
=> Upgrade testconatainers to 1.6.3

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/PreparedStatementAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UnicodeCharsTest.java
=> fix support for explicit nationalized characters

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyOneToManyAssociationWithFetchTest.java
Amazingly, it works!
fixes #1098
=> enable Query.setPlan()

gradle/wrapper/gradle-wrapper.properties
=> Upgrade Gradle to 6.9.2

.github/workflows/build.yml, README.md
=> Test with JDK 19

hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongCredentialsTest.java
This works now... I don't know why
=> Wrong credentials Test

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
[trivial]
Adding the ability to debug when a contextual session is being reused
=> Add some logging in relation to reuse of open Mutiny.Session found in context

README.md, documentation/src/main/asciidoc/reference/introduction.adoc, podman.md
Fixes #1192 
Not sure if we should mention something else.
=> Add the Oracle client GAV to the docs

release/build.gradle
It also uses the `--sparse` option.
@yrodiere @gsmet: You might want to have a look at this. I'm publishing the docs on hibernate.org but  it's easy to change this if we want to publish somewhere else on GItHub
=> Update the docs website without plugins

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactivePaddedBatchingCollectionInitializer.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchFetchTest.java
Fixes #1212 
We should call reactiveLoadColelction
=> Fix call to loadCollection

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UriPoolConfiguration.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/JdbcUrlParserTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DatabaseConfiguration.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/OracleDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/TestableDatabase.java
Fix #1059
Fix #864 
It now also uses the right default port for CockroachDB if none is defined
=>  Include connection parameters during the creation of SqlConnectOptions #1225 

hibernate-reactive-core/build.gradle
=> Upgrade to Mutiny 1.4.0

.github/workflows/build.yml, .github/workflows/tracking-orm-5.build.yml, .github/workflows/tracking-vertx-4.build.yml, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/StartVerticle.java, podman.md
=> Upgrade PostgreSQL image version to 14.2

hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
=> Remove warnings in BaseReactiveTest

release/build.gradle
* Use delete task for removing a folder
* Copy reference documentation from and to the right folder
=> Fix documentation publishing task

README.md, build.gradle, gradle.properties, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DockerImage.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/OracleDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/TestableDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/VertxMariaContainer.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/VertxMySqlContainer.java
For `jakarta/main`.
Add missing commits that are already in the `main` branch
=> Catch up with the main branch

hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReferenceTest.java
We are testing a possible solution for #1264
=> Test remove entity using id and reference in a tx

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/PostgresParameters.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionFactoryImpl.java
These are causing NoSuchMethodError on application startup
(this can be verified easily either via the debugger, or from JFR events - see
https://bugs.openjdk.java.net/browse/JDK-8161588 for more details
about why the error occurs) which can have a small impact on startup performance
N.B. I only replaced the code for the instances
that were causing the issue at the startup of a
Quarkus application that uses Hibernate Reactive
=> Remove some lambda expressions

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/vertx/impl/DefaultVertxInstance.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/InternalStateAssertionsTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/NoVertxContextTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToOnePrimaryKeyJoinColumnTest.java
=> Fix for no vertx context active message error

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/PostgresParameters.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionFactoryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/NoVertxContextTest.java
For #1291 
I've added some comments or people will revert the code as soon as they see it.
=> Cleanup for PostgresParameters

README.md, build.gradle
=> Upgrasde to ORM 5.6.9.Final

README.md, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/PostgresParameters.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionFactoryImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CachedQueryResultsGenerateStatisticsTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CachedQueryResultsTest.java
Add missing commits that are already in the main branch
=> Jakarta upgrade

hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessProxyUpdateTest.java
=> Check for CompletionStage before a StatelessSession#fetch

build.gradle, examples/native-sql-example/build.gradle, examples/session-example/build.gradle, hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UriPoolConfiguration.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, integration-tests/verticle-postgres-it/build.gradle, integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/StartVerticle.java, podman.md, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade docker images; Upgrade optional and testing dependencies

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x to 4.3.0

README.md, build.gradle, gradle.properties, hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UUIDAsBinaryType.java, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x to 4.3.1

hibernate-reactive-core/src/main/java/org/hibernate/reactive/bulk/impl/ReactiveIdTableSupport.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLUpdateQueryTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/JoinedSubclassInheritanceTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UnionSubclassInheritanceTest.java
=> Re-enable tests for Oracle

gradle.properties
=> Add Oracle to db list in gradle.properties

hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyInitializationExceptionWithMutiny.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyInitializationExceptionWithStage.java
=> Improve error message when lazy collection is not initialized

hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchingConnectionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/testing/SqlStatementTracker.java
The tests we had didn't check if we were running the right amount of queries - just the final results in the db.
Fixes #1333
=> Test batching

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEntityEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactivePaddedBatchingCollectionInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SQLServerParameters.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/MySqlReactiveInformationExtractorImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/OracleSqlReactiveInformationExtractorImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/SqlServerReactiveInformationExtractorImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CurrentUser.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeListTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeSetTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForEmbeddableTypeListTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForEmbeddedEmbeddableTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOrderedElementCollectionForEmbeddableTypeListTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLUpdateQueryTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MyCurrentTenantIdentifierResolver.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/OracleDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/testing/SqlStatementTracker.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesAndCallbacksForAllDBsTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/LobTypeTest.java
A collection of changes to remove warnings from IDEA (and cleaning the code in the process).
They should be safe but better if somebody else double check
=> Remove warnings

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/ReactiveCacheEntityLoaderHelper.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LockOnUpdateTest.java
=> fix for #1258

hibernate-reactive-core/build.gradle
=> Upgrade to Mutiny 1.6.0

build.gradle, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade testcontainers to 1.17.3

build.gradle
=> Upgrade Vert.x to 4.3.2

hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
Addresses session.clear() for #1365 and related to #1362
=> Add test cases for ReactiveSession#clear

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityIdentityInsertAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityInsertAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
=> miscellaneous minor changes

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
Fixes #600.
I'm not sure how I feel about this. It really is a significant amount of API bloat.
=> support for CacheRetrieveMode, CacheStoreMode, LockModeType, FlushModeType

hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrderQueriesTestBase.java
Fix #1287 
Follows https://github.com/hibernate/hibernate-reactive/pull/1370
@blafond I've refactored a bit your PR. Could you have a look at it and merge it, if you are happy with it, please?
Thanks
=> Test for 'hibernate.order_updates' and 'hibernate.order_inserts'

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade to Vert.x 4.3.3

build.gradle
=> Upgrade Hibernate ORM to 5.6.12.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java
=> implemented reactiveForceFlush() to fix UnsupportedOperationException

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java
=> A minor refactoring

hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompositeIdManyToOneTest.java
=> add failing test for #1384

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java, release/build.gradle
=> Fix docs release

README.md, build.gradle, gradle.properties, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrphanRemovalTest.java, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x to 4.3.4

tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Fix dependencies in the JBang scripts

README.md
fixes #1409
Signed-off-by: blafond <blafond@redhat.com>
=> [#1409] Add jbang template instructions

README.md, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateCockroachDBTestBase.java, podman.md, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
Upgrade Cockroach DB version to 22.1.9 and fix update schema test error
fixes #1407
=> Upgrade Cockroach DB to 22.1.9

.github/workflows/build.yml, README.md, build.gradle, hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaUpdateCockroachDBTestBase.java, integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/StartVerticle.java, podman.md, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
Add missing commits from the main branch
=> Jakarta branch updates

hibernate-reactive-core/build.gradle
=> Upgrade Mutiny to 2.0

hibernate-reactive-core/src/test/java/org/hibernate/reactive/BlockTableGeneratorTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CustomSqlTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CustomStoredProcedureSqlTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/DynamicUpdateTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerManyToOneAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOneToManyAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOneToOneAssociationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertySingleTableTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertyUnionSubclassesTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/IdentifierGenerationTypeTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/IdentityGeneratorTypeTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/InternalStateAssertionsTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/JdbcUrlParserTest.java
=> PostgreSQL results: FAILURE (800 tests, 541 passed, 221 failed, 38 skipped)

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/ast/spi/ReactivePostgreSQLSqlAstTranslator.java
This fixes the two failing tests in HQLQueryParameterPositionalTest without causing a new failures
=> Fix HQLQueryParameterPositionalTest

hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSelectionQueryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
PostgreSQL results: FAILURE (810 tests, 618 passed, 154 failed, 38 skipped)
=> implementation and tests for createSelectionQuery() Stage session methods

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveGeneratorWrapper.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveIdentifierGeneratorFactory.java
The fix is far from elegant, but unless we make
ORM more lenient, there is way around this hack
=> Fix CustomGeneratorTest

hibernate-reactive-core/build.gradle
Done by using the same EhCache configuration used in Hibernate ORM
=> Fix CacheTest

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x SQL client to 4.3.8

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/spi/ReactiveRowProcessingState.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/spi/ReactiveListResultsConsumer.java
Implement missing methods and extend BaseExecutionContext
=> Fix implementation of ReactiveRowProcessingState

build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/env/internal/ReactiveMutationExecutor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/mutation/internal/ReactiveMutationExecutorSingleSelfExecuting.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/mutation/internal/ReactiveMutationExecutorStandard.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/mutation/internal/ReactiveValueBindings.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/insert/ReactiveAbstractReturningDelegate.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/insert/ReactiveAbstractSelectingDelegate.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveDeleteRowsCoordinatorStandard.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveInsertRowsCoordinatorStandard.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveRemoveCoordinatorStandard.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveUpdateRowsCoordinatorOneToMany.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveUpdateRowsCoordinatorStandard.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveDeleteCoordinator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveInsertCoordinator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveUpdateCoordinatorStandard.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/cte/ReactiveCteInsertHandler.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/ReactiveStandardMutationExecutorService.java
It requires the latest ORM 6 snapshot.
With this we can apply the additional changes from @geoand for this PR: https://github.com/hibernate/hibernate-reactive/pull/1462
=> Update to the latest ORM snapshot

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/StandardReactiveSelectExecutor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CachedQueryResultsTest.java
This results in the failing tests going from 130 to 125
=> Fix CachedQueryResultsTest

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/StandardReactiveSelectExecutor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerTest.java
This brings the number of failing tests from `87` to `83`
=> Introduce some FetchType.EAGER support

hibernate-reactive-core/src/test/java/org/hibernate/reactive/FetchedAssociationTest.java
The assertion of the test needed to updated to the ORM 6 generated queries (the queries as essentially the same, but the sequences and names of variables have changed).
Furthermore, the custom cleanup is done because the actual test itself passes (with the updated assertion), but the DB clearing fails because of the association loading issue.
=> Fix FetchedAssociationTest

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerUniqueKeyTest.java
The custom cleanup is done because the actual test itself passes, what fails before this change is the loading of entities which occurs when the database is being cleared during test cleanup.
Furthermore, fix erroneous assertion in `EagerUniqueKeyTest`.
After this change, only `testMergeReference` fails (whereas before all tests failed) with:
```
java.util.concurrent.CompletionException: org.hibernate.HibernateException: java.util.concurrent.CompletionException: org.hibernate.AssertionFailure: non-transient entity has a null id: org.hibernate.reactive.EagerUniqueKeyTest$Bar$HibernateProxy$scYAEL1t
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) …
```
=> Partially fix EagerUniqueKeyTest

hibernate-reactive-core/src/test/java/org/hibernate/reactive/NonNullableManyToOneTest.java
Furthermore, use property access instead of field access
=> Work around lazy eager loading issue in clean DB for NonNullableManyToOneTest

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/mutation/internal/ReactiveMutationExecutorPostInsert.java
With this change, the failing tests go from 65 to 63
~~P.S. A Hibernate ORM [change](https://github.com/hibernate/hibernate-orm/pull/6182) is required.~~ Done
=> Implement ReactiveMutationExecutorPostInsert

hibernate-reactive-core/src/test/java/org/hibernate/reactive/InsertOrderingReferenceSeveralDifferentSubclassBase.java
The only thing that changes is the whitespaces generated by ORM
=> Fix InsertOrderingReferenceSeveralDifferentSubclassBase tests

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleUniqueKeyEntityLoaderStandard.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/metamodel/mapping/internal/ReactiveToOneAttributeMapping.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractPersisterDelegate.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/StandardReactiveSelectExecutor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/spi/ReactiveRowProcessingState.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/ReactiveDomainResultsAssembler.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/ReactiveInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/ReactiveAbstractEntityInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntityAssembler.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntityDelayedFetchInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntityFetchSelectImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntityResultInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchByUniqueKeyInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchInitializer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchInitializerBuilder.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveEntityResultImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveInitializersList.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveResultsHelper.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveStandardRowReader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/domain/ReactiveCircularFetchImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/spi/ReactiveListResultsConsumer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/spi/ReactiveResultsConsumer.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/spi/ReactiveRowReader.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyOneToOneWithJoinColumnTest.java
Requires https://github.com/hibernate/hibernate-orm/pull/6230
@Sanne this should fix several tests
=> Custom initializers for Hibernate Reactive

integration-tests/bytecode-enhancements-it/build.gradle, integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/Crew.java, integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/lazytoone/Captain.java, integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/lazytoone/Ship.java, integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java, integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/LazyBasicFieldTest.java, integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/LazyOneToOneBETest.java, settings.gradle
There are a couple tests failing; I've disabled those and opened issues to match them.
=> Enable integration tests with bytecode enhancer

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/ReactiveQuery.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveExceptionConverter.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java
Resolved some warnings from the build
=> Formatting of javadoc

build.gradle, gradle.properties, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveAbstractCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java
=> Upgrade to Hibernate ORM 6.2.0.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveTypeContributor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UTCTest.java
=> Enable UTC for Oracle

build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityDeleteAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/testing/ReactiveAssertions.java
=> Upgrade Hibernate ORM to 6.2.1.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/ReactiveDomainResultsAssembler.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveEntityResultJoinedSubclassImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/issue/JoinedSubclassInheritanceWithManyToOneTest.java
=> Error with JOINED inheritance and ManyToOne

build.gradle, examples/native-sql-example/build.gradle, examples/session-example/build.gradle, hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java, integration-tests/bytecode-enhancements-it/build.gradle, podman.md, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade  libraries

build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/FilterWithPaginationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/UUIDAsBinaryTypeTest.java
Fix #1629 
Fix #1596
Fix #1560 
Fix #1559
We still need to wait for Quarkus to upgrade
=> Upgrade Vert.x to 4.4.2

build.gradle, hibernate-reactive-core/build.gradle, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, mytest.java, podman.md, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
Fix #1626 
Fix #1651 
Fix #1653 
Fix #1652 
Fix #1654
=> Update test dependencies and fix JBang examples 

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveActionQueue.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/temptable/ReactiveTableBasedUpdateHandler.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/temptable/ReactiveUpdateExecutionDelegate.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedIdentityGenerationTest.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedInsertionTest.java
=> Minor fixes

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/PreparedStatementAdaptor.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/LobTypeTest.java
Fix #1500 
Added a couple of commits on top of https://github.com/hibernate/hibernate-reactive/pull/1657
=> Fix LobtypeTest except for Db2 and Pg

build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/iternal/ReactiveSimpleDeleteQueryPlan.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/cte/ReactiveAbstractCteMutationHandler.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/cte/ReactiveCteInsertHandler.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/temptable/ReactiveExecuteWithTemporaryTableHelper.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/temptable/ReactiveUpdateExecutionDelegate.java
=> Upgrade ORM to 6.2.5.Final

README.md, build.gradle
=> Upgrade credentials gradle plugin to 2.2

build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveDeleteRowsCoordinatorStandard.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveRemoveCoordinatorStandard.java
Fix #1717 
@gavinking, the problem was [a missing return statement](https://github.com/hibernate/hibernate-reactive/commit/676b724eaef22a453be3b4f4d298db1faf1fcd0b) in Hibernate Reactive.
=> Upgrade Hibernate ORM to 6.2.7.Final

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x SQL client to 4.4.5

README.md, build.gradle, hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityDeleteAction.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveDeleteCoordinator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/RowIdUpdateAndDeleteTest.java
Fix #1767 because we need Hibernate ORM 6.3.1.Final
Fix #1756 
I made a mistake and [merged this PR too soon](https://github.com/hibernate/hibernate-reactive/issues/1756)
This is the correct PR to merge when  https://hibernate.atlassian.net/browse/HHH-17167 has been merged in Hibernate ORM
=> Rowid with deletes

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x SQL client to 4.4.6

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x and Hibernate ORM

build.gradle
=> Upgrade nu.studer.credentials gradle plugin to 3

README.md, build.gradle
=> Upgrade Hibernate ORM to 6.4.2.Final

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x SQL client to 4.5.3

README.md, build.gradle, gradle.properties
=> [#1897] Upgrade Hibernate ORM to 6.5.0.Final

tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> [#1899] Upgrade JBang templates to 2.3.0.Final

.github/workflows/build.yml
Fix #1917 
It's not available anymore from jdk.java.net
=> Fix CI failure setting up JDK 21

README.md, build.gradle, gradle.properties
=> Upgrade Hibernate ORM to 6.5.1.Final

hibernate-reactive-core/build.gradle
=> Upgrade PostgreSQL jdbc driver to 42.7.3

tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Hiberante Reactive in the JBang template to 2.3.1.Final

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> For main, Upgrade Vert.x SQL client to 4.5.9 

.github/workflows/build.yml
It wasn't building PR
Fix #1970
=> Fix issues with GitHub actions

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Hibernate ORM to 6.6.0.Final

.github/workflows/build.yml
=> Upgrade actions/upload-artifact

.github/workflows/build.yml, README.md
=> Update JDK for testing

hibernate-reactive-core/src/main/java/org/hibernate/reactive/type/descriptor/jdbc/ReactiveJsonJdbcType.java
Minor additional commit for #1984
=> Replace `toString` with `JsonObject#encode`

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x SQL client to 4.5.11

README.md, gradle.properties
=> Upgrade Hibernate ORM to 6.6.3.Final

gradle/version.properties
Missing part fro #1895 
I forgot to update the development version
=> Change development version to 3.0.0-SNAPSHOT

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
see https://github.com/hibernate/hibernate-reactive/issues/2042
=> #2042 add insertMultiple() and friends, with semantics aligned with ORM 7

ci/release/Jenkinsfile
=> Add missing comma to JenkinsFile

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdWithManyTest.java
=> Add assertions to the test

README.md, gradle.properties
=> Upgrade Hibernate ORM to 6.6.5.Final

examples/native-sql-example/build.gradle, examples/session-example/build.gradle, integration-tests/hibernate-validator-postgres-it/build.gradle
=> Upgrade Hibernate Validator to 8.0.2.Final for 2.4

examples/native-sql-example/build.gradle, examples/session-example/build.gradle, integration-tests/hibernate-validator-postgres-it/build.gradle
=> Upgrade Hibernate Validator to 8.0.2.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToOneMapsIdAndGeneratedIdTest.java
Fix https://github.com/hibernate/hibernate-reactive/issues/1904
=> PropertyAccessException when creating a new object with a one-to-one association

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveUpdateRowsCoordinatorOneToMany.java
=> [2.4] Don't ignore return value of deleteRows

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
Fix #2084 for Hibernate Reactive 2.4
=> [2.4] Upgrade Vert.x SQL client to 4.5.12

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x SQL client to 4.5.12

README.md, gradle.properties
=> Upgrade Hibernate ORM to 6.6.6.Final

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
Backport https://github.com/hibernate/hibernate-reactive/pull/2118
=> [2.4] Upgrade Vert.x SQL client to 4.5.13

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java, integration-tests/hibernate-validator-postgres-it/src/test/java/org/hibernate/reactive/it/quarkus/qe/database/BaseReactiveIT.java, integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/VertxServer.java, podman.md, tooling/jbang/Example.java, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade PostgreSQL for testing to 17.4

.github/workflows/build.yml
=> Remove JDK 23 for testing, enable JDK 24 GA

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java
Fix #2152 
It's not needed anymore
=> Remove experimental table support when starting CockroachDB

.github/workflows/build.yml
fixes https://github.com/hibernate/hibernate-reactive/issues/2169
for 2.4 branch
=> Use temurin for JDK 23 builds

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableInitializerImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchInitializer.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdWithManyEagerTest.java
Fixes https://github.com/hibernate/hibernate-reactive/issues/2166
=> [#2166] Hibernate Reactive eager fetching the wrong record for ManyToOne

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveNonAggregatedIdentifierMappingInitializer.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ManyToOneIdClassTest.java
=> [2.4] Backports NPE error

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x SQL client to 4.5.14

.github/workflows/build.yml, README.md, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java, integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java, integration-tests/hibernate-validator-postgres-it/src/test/java/org/hibernate/reactive/it/quarkus/qe/database/BaseReactiveIT.java, integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/VertxServer.java, podman.md, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> [2.4] Update databases and README

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/ContextualDataStorage.java
It shouldn't be allowed to change it.
=> Make CONTEXTUAL_DATA_KEY constant

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/ContextualDataStorage.java
=> [2.4] Contextual constant

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
since JPA has this, and a uniform API makes things easier for Hibernate Processor
=> add getCriteriaBuilder() convenience method to session types

.gitignore, .release/.gitignore, build.gradle, ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, jreleaser.yml, publish.gradle, release/build.gradle
Backport https://github.com/hibernate/hibernate-reactive/pull/2223, https://github.com/hibernate/hibernate-reactive/pull/2245, and https://github.com/hibernate/hibernate-reactive/pull/2248 to the 2.4 branch
=> [2.4] Release using JRelease

README.md, gradle.properties
I doesn't require any changes, but I need it to merge https://github.com/hibernate/hibernate-reactive/pull/2199
=> Upgrade Hibernate ORM to 6.6.15.Final

README.md, build.gradle, gradle.properties, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
Fix #2261
We should wait until Quarkus upgrades this too
See https://github.com/quarkusio/quarkus/blob/4abbcf233f6e75bc86ab070ad3d40ada0502e0e3/bom/application/pom.xml#L114
=> Upgrade Vert.x to 4.5.15 (from 4.5.14)

hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLQueryTest.java
Supersedes https://github.com/hibernate/hibernate-reactive/pull/2280
Closes #1793
=> Test HQL `new` operator with many-to-one

hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLQueryTest.java
Backport https://github.com/hibernate/hibernate-reactive/issues/1793 (PR https://github.com/hibernate/hibernate-reactive/pull/2281) to 2.4
=> [2.4]  Test HQL new operator with many-to-one

hibernate-reactive-core/src/main/java/org/hibernate/reactive/metamodel/mapping/internal/ReactiveEmbeddedIdentifierMappingImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableAssembler.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableFetchImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableInitializerImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntityInitializerImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdWithOneToOneTest.java
Supersedes https://github.com/hibernate/hibernate-reactive/pull/2279
Fix #2230
=> ClassCastException when with @EmebedddedId and @OneToOne relationship

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableFetchImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableInitializerImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/ManyToOneMapsIdAndEmbeddedIdTest.java
=> ClassCastException with MapsId, EmbeddedId, and many-to-one

README.md, gradle.properties
=> Upgrade Hibernate ORM to 7.0.1.Final

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/ReactiveIdentifierGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveCompositeNestedGeneratedValueGenerator.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/tuple/entity/ReactiveEntityMetamodel.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompositeIdWithGeneratedValuesTest.java
Backport #2154 (PR #2303) to the 3.0 branch
=> [3.0] Composite key with generated value not working properly

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, publish.gradle
=> Switch to Maven Central publishing (main)

.github/workflows/build.yml
=> Add JDK 26-ea to the build

.github/workflows/build.yml
Backport #2309 (PR #2310) for 2.4
=> [2.4] Add JDK 26-ea to the build

ci/release/Jenkinsfile
Backport of #2319 + enable auto-release on weekends.
=> [2.4] Release job alignment on Hibernate ORM + improvements

build.gradle, documentation/build.gradle, examples/native-sql-example/build.gradle, examples/session-example/build.gradle, gradle.properties, gradle/libs.versions.toml, hibernate-reactive-core/build.gradle, integration-tests/bytecode-enhancements-it/build.gradle, integration-tests/hibernate-validator-postgres-it/build.gradle, integration-tests/techempower-postgres-it/build.gradle, integration-tests/verticle-postgres-it/build.gradle, local-build-plugins/src/main/java/org/hibernate/reactive/env/VersionsPlugin.java, local-build-plugins/src/main/java/org/hibernate/reactive/env/VersionsTomlParser.java, settings.gradle
Backport #1989 (PR #2331) to 3.0
=> [3.0] Migrate to Gradle version catalogs

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableInitializerImpl.java
Fix #2381 
The code was using .thenAccept instead of .thenCompose
=> Fix chaining in ReactiveEmbeddableInitializerImpl#reactiveResolveInstance

gradle.properties, gradle/libs.versions.toml, settings.gradle
And realign the Hibernate Gradle Plugin to the same version
=> [3.1] Update Hibernate ORM to 7.1.0.Final

README.md, gradle.properties, gradle/libs.versions.toml, tooling/jbang/CockroachDBReactiveTest.java.qute, tooling/jbang/Db2ReactiveTest.java.qute, tooling/jbang/Example.java, tooling/jbang/MariaDBReactiveTest.java.qute, tooling/jbang/MySQLReactiveTest.java.qute, tooling/jbang/PostgreSQLReactiveTest.java.qute, tooling/jbang/ReactiveTest.java
=> Upgrade Vert.x to 5.0.2

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveLoaderHelper.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/internal/ReactiveCacheLoadHelper.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/LockOnLoadTest.java
Supersedes https://github.com/hibernate/hibernate-reactive/pull/2371
Rebased over `main`
Fix #2332
=> "Not using JDBC" when locking previously loaded entities in Hibernate Reactive 3

.github/dependabot.yml, .github/workflows/codeql.yml
Follows https://github.com/hibernate/hibernate-reactive/pull/2477
=> Include branch 4.1 in the CI checks and dependabot

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/BatchingConnection.java
Backport #2535 (PR #2536) for `3.1`
=> [3.1] Fix operations order in BatchingConnection

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java, hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java, hibernate-reactive-core/src/test/java/org/hibernate/reactive/FindByIdWithLockTest.java
=> [4.2] Session.find should respect the nowait lock

ci/release/Jenkinsfile, release/build.gradle
Backport https://github.com/hibernate/hibernate-reactive/issues/2519 (PR https://github.com/hibernate/hibernate-reactive/pull/2531) for 4.1
=> [4.1] Migrate to release scripts for documentation publishing
