hibernate/hibernate-reactive

build.gradle
hibernate-rx-api/build.gradle
hibernate-rx-core/build.gradle

For two reasons:
1- ensure the versions are aligned among components (e.g. same version of `hibernate-core` as `hibernate-testing`
2- allows to easily check compatibility with a different version
In particular, I'm thinking to setup a CI job which will monitor both existing ORM tags and next upcoming snapshots. 
./gradlew clean build -PhibernateOrmVersion=5.4.13-SNAPSHOT
That's not to say we need to strive to have master pass with multiple versions of ORM, but to be aware and informed: we can then decide ad-hoc.

Extract the Hibernate ORM version into a build parameter

---

hibernate-rx-core/src/main/java/org/hibernate/rx/event/impl/DefaultRxLoadEventListener.java
hibernate-rx-core/src/main/java/org/hibernate/rx/impl/RxSessionInternalImpl.java
hibernate-rx-core/src/main/java/org/hibernate/rx/util/impl/RxUtil.java

I left commit https://github.com/hibernate/hibernate-rx/commit/cc126844ee9d5c1b75e38826a651b9f0a11d8e30 to show what's the piece of code causing issues. But it requires the use of a blocking method.
The final fix is more complicated but I think it highlights better what's going on.
This patch is simpler than  https://github.com/hibernate/hibernate-rx/pull/66 and doesn't require the ORM dependency update.
The assumption I'm making here is that we only return a CompletionStage when we load the entity from the datasource and in all the other cases we return a proxy.
I removed the comment about checkIdClass because I think it was a mistake the way we implemented it. I will create an issue to make sure that we test that use case.

65 Fix master build

---

.travis.yml
README.md
gradle/wrapper/gradle-wrapper.properties
hibernate-rx-core/build.gradle
hibernate-rx-core/src/test/java/org/hibernate/rx/BaseRxTest.java
hibernate-rx-core/src/test/java/org/hibernate/rx/MySQLAutoincrementTest.java
hibernate-rx-core/src/test/java/org/hibernate/rx/MySQLBasicTest.java
hibernate-rx-core/src/test/java/org/hibernate/rx/TestConfiguration.java
hibernate-rx-core/src/test/resources/log4j.properties

Added a docker/testcontainers option of running the tests. People can now run all tests with `./gradlew test -Pdocker` without needing to do any other setup (aside from having docker installed).
Also added TravisCI pipeline that will run all tests in a single stage.

Add Testcontainers and CI Pipeline

---

hibernate-rx-core/build.gradle

Issue: https://github.com/hibernate/hibernate-rx/issues/86
I think there is too much information on the console right now during the build and it hides which test has failed. I guess on CI it would be handy but we can find an alternative to enable it if we need it.
A bit unrelated but I've noticed that the execution time for each test doesn't appear. Is there a way to enable it?
Note that running `gradle build -i` will produce the same output when nothing is cached.

86 Reduce test logging during build

---

hibernate-rx-core/src/main/java/org/hibernate/rx/engine/impl/Cascade.java
hibernate-rx-core/src/main/java/org/hibernate/rx/engine/impl/RxPersistenceContextAdapter.java
hibernate-rx-core/src/main/java/org/hibernate/rx/event/impl/DefaultRxDeleteEventListener.java
hibernate-rx-core/src/main/java/org/hibernate/rx/event/impl/DefaultRxInitializeCollectionEventListener.java
hibernate-rx-core/src/main/java/org/hibernate/rx/impl/RxSessionInternalImpl.java
hibernate-rx-core/src/main/java/org/hibernate/rx/jpa/impl/RxPersisterClassResolver.java
hibernate-rx-core/src/main/java/org/hibernate/rx/loader/RxOuterJoinLoader.java
hibernate-rx-core/src/main/java/org/hibernate/rx/loader/collection/RxCollectionLoader.java
hibernate-rx-core/src/main/java/org/hibernate/rx/loader/collection/RxOneToManyJoinWalker.java
hibernate-rx-core/src/main/java/org/hibernate/rx/loader/collection/RxOneToManyLoader.java
hibernate-rx-core/src/main/java/org/hibernate/rx/persister/persister/collection/RxOneToManyPersister.java
hibernate-rx-core/src/main/java/org/hibernate/rx/service/RxIntegrator.java
hibernate-rx-core/src/main/java/org/hibernate/rx/util/impl/RxUtil.java
hibernate-rx-core/src/test/java/org/hibernate/rx/LazyOneToManyAssociationWithFetchTest.java

Follows https://github.com/hibernate/hibernate-rx/pull/82
@gavinking I had to change the commit for `fetchLazyAssociationBeforeCascade` because the stages weren't executed in the right order: https://github.com/hibernate/hibernate-rx/compare/master...DavideD:35-fetch-one-to-many-v2?expand=1#diff-1e7a64ba50be1d2c2ccc008faf2e4883R86
It seems that now all the tests are succesfull

35 Fetch bidirectional lazy one-to-many associations v2

---

build.gradle
hibernate-rx-api/build.gradle
hibernate-rx-api/src/main/java/org/hibernate/rx/RxSession.java
hibernate-rx-core/build.gradle
hibernate-rx-core/src/main/java/org/hibernate/rx/event/impl/DefaultRxDeleteEventListener.java
hibernate-rx-core/src/main/java/org/hibernate/rx/event/impl/DefaultRxFlushEventListener.java
hibernate-rx-core/src/main/java/org/hibernate/rx/persister/entity/impl/RxAbstractEntityPersister.java
publish.gradle

Adds the `hibernate-rx-api` and `hibernate-rx-core` modules as publishable modules. This makes it so when you do `./gradlew publish` or `./gradlew publishToMavenLocal` the build will publish the maven artifacts to your local Maven repo.
There is now a common publish script at publish.gradle and any sub-module that wants to publish a maven artifact can do `apply from: publishScript` in their build.gradle file.

Add gradle script for publishing as Maven publication

---

LICENSE
README.md

I noticed that there is no license currently associated with this project. Since Hibernate ORM uses LGPL 2.1 license, I assume we would want to use the same license here.
This PR adds the necessary LGPL 2.1 metadata and also adds a build status badge to the readme

Add LGPL 2.1 license

---

gradle/wrapper/gradle-wrapper.properties

Useful when dealing with Gradle builds.

Switch to use the Gradle wrapper version with sources

---

.github/workflows/build.yml
README.md
hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/test/java/org/hibernate/reactive/AutoincrementTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseMutinyTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BasicTypesAndCallbacksTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompositeIdTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/DB2BasicTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/FilterTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MySQLAutoincrementTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MySQLBasicTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/ReactiveConnectionPoolTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DatabaseConfiguration.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/VertxMySqlContainer.java

Part of #61 
This PR does not change default behavior at all (all tests will still run with Postgresql by default), but it adds the ability to easily change any test to run with different DB types.  For example, to run all tests with DB2, you can do the following:
./gradlew test -Pdocker -Pdb=db2
Currently supported values are: postgresql, pg, postgres, db2, and mysql (all case insensitive)
If you specify an invalid option, you get an error saying what you specified and what the valid values are.
More importantly, this will greatly increase our test coverage because CI can repeat all of our tests with different DB types. For now I've just enabled DB2, but will circle back and enable MySQL in a later PR.
There will always be special cases where a certain test may only work for a specific …

Database rotation

---

example/build.gradle
hibernate-reactive-core/build.gradle

Fixes #126
I've copied the example into a standalone Maven project, so to verify it and see how it would look like:
- https://github.com/Sanne/reactive-maven-demo/blob/master/pom.xml#L11-L24
To see the pom.xml file generated for this project, run:
./gradlew generatePomFileForMavenJavaPublication
You can them open it from `hibernate-reactive-core/build/publications/mavenJava/pom-default.xml`
This also generates Gradle specific metadata, which is more powerful as it can express more details, but it's only useful for user applications built via Gradle.

Review the project's dependency metadata

---

podman.md

* DB2 server start without sudo
* Remove --memory-swappiness=0 from Postgres (requires root)
@Sanne I noticed that DB2  actually works without sudo on my machine but it ends on the console without a clear message and looks like it's not started. Could you try these changes and let me know?
Postgres wasn't working with the --memory-swappiness=0 option.
@gbadner Could you test these as well when you have a minute? Thanks

Fix podman scripts

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/boot/impl/ReactiveTypeContributor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/boot/service/NoJdbcEnvironmentInitiator.java
hibernate-reactive-core/src/main/resources/META-INF/services/org.hibernate.boot.model.TypeContributor
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BasicTypesAndCallbacksTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java

So here's a little bit of an experiment with `BLOB`/`CLOB` support.
I had to mess with the Hibernate `Dialect`s, because by default they use `Stream`s or actual `java.sql.Blob` \ `java.sql.Clob` objects to bind LOB parameters.
So I'm passing:
- a Vert.x `Buffer` for the `BLOB`, and
- a `String` for the `CLOB`.
This works on Postgres and MySQL, but not quite on DB2, since the DB2 client doesn't support binding `Buffer`s (cc @aguibert).
But @vietj is this the right thing to do? Is there some better way more specialized way we should be reading and writing LOBs?
See #96.

testing @Lob

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/boot/impl/ReactiveIntegrator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CascadingActions.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveAutoFlushEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLockEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveMergeEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactivePersistEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveRefreshEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/spi/ReactiveLockEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java

I have hacked together some sort of support for the `lock()` method.
The only supported lock modes (for now) are:
- ` PESSIMISTIC_WRITE`
- `PESSIMISTIC_READ`
There are no `LockingStrategy`s, this is hardcoded for now.
see #142

lock() method

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnectionPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java

This is a request from @aguibert.
Currently `SessionFactory.openSession()` returns a `CompletionStage`. This would add an additional operation that gives you a `Session` with no `CompletionStage`, fetching the database connection lazily.
Would like some feedback on this issue.

add SessionFactory.createSession()

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/boot/impl/ReactiveTypeContributor.java

This patch ensures that we generate the right column types for properties mapped `@Lob`.

DDL generation for @Lob

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/CachingReactiveLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/custom/impl/ReactiveCustomLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactivePlanEntityLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/hql/impl/ReactiveQueryLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveCriteriaQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryTranslatorImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLUpdateQueryTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java

This patch extends @gbadner's work on query parameters by adding:
- positional + named parameters in native queries
- named + anonymous parameters in criteria queries
But for now I could not figure out how to add support for parameters in update/delete queries or criteria.

support for parameters in native and criteria queries

---

build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/CachingReactiveLoader.java

@gavinking can you have a look at this?
The problem is that CachingReactiveLoader#bindPreparedStatement scope is in conflict with Loader#bindPreparedStatement
Adding the merhod in Loader was part of this PR: https://github.com/hibernate/hibernate-orm/pull/3420
that was sent during the work to support parameters https://github.com/hibernate/hibernate-reactive/pull/197
Renaming the method in CachingReactiveLoader seems the simplest trick for now.

[#223] Upgrade to ORM 5.4.17.Final

---

.github/workflows/build.yml
build.gradle
gradle/version.properties
publish.gradle
release/build.gradle
settings.gradle

Follows up on #122 
To release, just run this from your clone of the repo:
```
./gradlew ciRelease -PreleaseVersion=0.0.1.Alpha1 -PdevelopmentVersion=1.0.0-SNAPSHOT -PgitRemote=upstream -PgitBranch=master
```
This will switch to your local copy of the branch `master`, create a commit that changes the version to `0.0.1.Alpha1` and tag it as `0.0.1.Alpha1`, then create another commit that changes the version to `1.0.0-SNAPSHOT`, then push those commits to branch `master` on remote `upstream` along with the tag.
Then GitHub actions will run tests, and finally create the packages and publish them to bintray, here: https://bintray.com/beta/#/hibernate/artifacts/hibernate-reactive?tab=overview
I'll submit another PR later to also push the javadoc to jboss.org.

Automated release

---

README.md
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerTest.java

So apparently some good person (either @gbadner or @DavideD or perhaps a combination of both) already implemented support for eager select fetching for collections.
This is half of #39 done!
This was something we had agreed we didn't need to support yet, and it's a carefully-documented limitation in the README, but I'm certainly not complaining!
Anyway I've added a test, just in case we didn't have a very explicit one already.

tests for eager fetching of collections

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/QueryParametersAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryTranslatorImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLUpdateQueryTest.java

See #220
Currently, multi-table updates and deletes are not supported.
This fix makes `HQLUpdateQueryTest#testUpdateQuery` pass. I have not tried other tests yet.
I suspect we would be better off using something like BasicExecutor instead. I'll look into this further next week,

Support parameters for update/delete queries

---

.github/workflows/build.yml

GitHub changed some things last weekend, and they are apparently pushing
for secret names to be all-caps.
I already changed the repo configuration accordingly.

Uppercase all GitHub secret names

---

.github/workflows/build.yml
build.gradle
documentation/build.gradle
documentation/src/main/asciidoc/reference/getting-started.adoc
documentation/src/main/asciidoc/reference/index.adoc
documentation/src/main/asciidoc/reference/preface.adoc
documentation/src/main/javadoc/overview.html
publish.gradle
release/build.gradle
settings.gradle

Fixes #230 
~Based on #242 , which should be merged first.~ => Done, and I rebased this on master.
The reference documentation is just a stub for now, but the javadoc may be helpful.
I already added the necessary secrets to this repository, so after this PR is merged the documentation will be published automatically (EDIT: when we release).
I tested the process on my fork and the documentation was successfully uploaded.
To have a look at the produced documentation:
```
./gradlew assembleDocumentation
xdg-open release/build/documentation/javadocs/index.html
xdg-open release/build/documentation/reference/html_single/index.html
````
(`xdg-open` works on Fedora; if you're on Mac OS, I'm not sure.)

Add a reference documentation module and publish documentation (reference + javadoc) upon release

---

README.md

This showcases the latest released version, and links to dependency instructions.
Should we add it?

Showcase the latest released version

---

.github/workflows/build.yml
publish.gradle

I wasn't able to test this all the way through, for obvious reasons, but I checked that the call to the Bintray Rest API responsible for triggering the Maven Central sync actually happens.
I added the necessary secrets to the repository, but I'm not sure I have the correct username/password. What I found was the username and password for the Sonatype OSSRH JIRA account, so I used that, hoping a single set of credentials is used throughout all Sonatype applications.
Normally, the user and password are saved in the configuration of the Hibernate Organization on Bintray, but I don't have administrative rights to that organization.
@Sanne Could you please check the username password under the "Accounts" section of the Hibernate Organization on Bintray match the username and password we have …

Sync artifacts with Maven Central upon release using the bintrayPublish task

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java

There are a couple of lines that are necessary for our tests
to work with MySQL but shouldn't impact users.

Isolate code required for MySQL in test suite

---

build.gradle
example/build.gradle
hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DatabaseConfiguration.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/TestableDatabase.java

This code PR contains several minor changes:
* Extract version of Vert.x and Testcontainers in properties
* Allow all the databases to have aliases (not only Postgres)
* Upgrade testcontainers to version 1.14.3 (because, why not?)
None of these changes are essential but I think they will come in handy when adding new databases.

Refactoring for DatabaseConfiguration

---

README.md
build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/SerializableExceptionTest.java

I think I've found a bug in the vertx client for MySQL.
Disabling the query cache solves the issue.
We have a query that has a Buffer as parameter. If the first time we run the query the parameter is null, the client will infer the type in `DataTypeCodec#inferDataTypeByEncodingValue` as `DataType.NULL` instead of `DataType.BLOB`. It seems that at that point the value is cached and therefore the encoding changes depending on when you run the query.
For now I've disabled the cache for MySQL so that we can upgrade.
@aguibert Would you be able to have a look at this, please?

287 Upgrade to vert.x sql client 3.9.2

---

documentation/src/main/asciidoc/reference/introduction.adoc
hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQueryExecutor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveHQLQueryPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeSQLQueryPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CacheTest.java
hibernate-reactive-core/src/test/resources/ehcache.xml

- add `SessionFactory.getCache()`
- add some basic tests for EHCache
For #184

initial support for second-level cache

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveActionQueue.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveAfterTransactionCompletionProcess.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveBeforeTransactionCompletionProcess.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityIncrementVersionProcess.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityVerifyVersionProcess.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLockEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactivePostLoadEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveIntegrator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java

These `LockMode`s force a version check or upgrade right at the end of the transaction.
This required building infrastructure for reactive before/after transaction completion events.
Fixes #201
Still TODO: support passing `OPTIMISTIC`, `OPTIMISTIC_FORCE_INCREMENT` to `session.lock()`

support for OPTIMISTIC + OPTIMISTIC_FORCE_INCREMENT LockModes

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/Cascade.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CascadingAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CascadingActions.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JoinColumnsTest.java

During the noCascade action Hibernate Reactive was calling the non reactive `ForeignKeys.isTransient `.

[#342] Support reactive no cascade action

---

hibernate-reactive-core/src/test/resources/log4j2.properties

It is not user friendly for people with some type of colour blindness.
Please, let's try to avoid changing the default colours in the project. It's very personal and everybody is more than capable of customising the working environment if needed

Remove layout property for logs

---

.github/workflows/tracking-orm-5.4.build.yml
.github/workflows/tracking-vertx-3.build.yml
build.gradle
example/build.gradle

This approach uses GitHub workflows, the JBoss Snapshots repository to download the latest 5.4 ORM SNAPSHOT and will be triggered by push  or pr on master and every hour via a cron job.
I'm testing and running the examples on all dbs but I think a simpler version that runs on Postgres might be enough. I've created it on a separate branch: https://github.com/DavideD/hibernate-reactive/pull/8
I've added a workflow to test 5.5 as well so that I can see that it fails for it but we can remove it for now.
If we want to build the project when ORM build, I will have to look into Jenkins.

[#361] Track ORM 5.4 snapshots

---

.github/workflows/tracking-vertx-3.build.yml

The schedule jobs don't fail anymore and I think I was just confused about which job caused the issues.
I took the chance to change how we print the selected library

[#407] Use dependency insight for vertx version

---

release/build.gradle

I've used this plugin: https://github.com/ajoberstar/gradle-git
Do we still want to publish on the JBoss doc server? For now I've removed it
I've tested it locally but we need to wait for the release to see if it actually works.
Better merge this after we merged the reactive website: https://github.com/hibernate/hibernate.org/pull/155

[#419] Publish the documentation on hibernate.org

---

build.gradle
gradle.properties

In order to work around illegal accesses in Gradle.
Workaround for https://github.com/gradle/gradle/issues/15538
This should fix the JDK16 build.
Signed-off-by: Yoann Rodière <yoann@hibernate.org>

Add --add-opens options required for Gradle

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/InternalStateAssertions.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ProxyConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java

I'm introducing some assertions, which are now passing after Davide's #478 (They didn't pass before).
I know we don't often use `assert`, but I feel it's a good compromise in this context:
- we're only focusing on Vertx currently
- we need to nail down our design mistakes
- it's not going to bother anyone at runtime, other than tests and people who enable assertions
WDYT ?

Thread and EventLoop context Assertions

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveGenerationTarget.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongCredentialsTest.java

Fixes #494
Note that the example will print the error but will still get stuck.
I think that's because we use `join()` or `await().indefinetly()`

[#494] Wrong credentials cause Thread to wait forever

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompositeIdTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java

I have no clue how we didn't notice this earlier.
I was bugging @cescoffier a couple of days ago because my `Uni`s weren't being serialized, and it turns out we were using `invoke()` to chain `Uni`s in the test. How embarrassing.

fix broken use of streams in populateDB() in tests

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java

See #480.
Previously, work could be done on the calling thread, outside of a Vert.x context.
This code makes the Mutiny API do work lazily, dispatching it to the Vert.x context.
Open questions:
- Is it too expensive to do this for *every* operation? Should we only do it in `withSession()` / `withTransaction()`, and just make the other operations lazy, but not dispatch them to the Vert.x context?
- How do I do this with `CompletionStage`s?
- Is this code actually correct, @vietj @cescoffier?

run all operations in a Vert.x context

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/InternalStateAssertions.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultipleContextTest.java

Resolves #479 
It's currently considered an error to share a Session between
multiple reactive streams, so we should detect that condition
and throw an exception.

[#479] Test exception when sharing session between contexts

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveResultSetProcessor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java

Resolves #507
I rewrote the methods we use for loops so that we don't need the dependency to asyncUtil.
I assumed it was responsible for the creation of the object causing the issue.
I'm not sure if there is more we can do considering that we will have to loop through the objects one way or the other.

[#507] Rewrite loops methods to improve performance

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveActionQueue.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveCollectionRecreateAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveCollectionRemoveAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveCollectionUpdateAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveFlushingEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveBasicCollectionLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveBatchingCollectionInitializerBuilder.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveCollectionPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactivePersisterClassResolver.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeListTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeSetTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForEmbeddableEntityTypeListTest.java

Added support for List, Set and List<{Embeddable Entity}>
Tests include:
- insert, remove, replace, clear elements
- duplicate and null elements.
- clearing of generated collection tables on delete of primary table
Logged be logging issues to address support for
- @OrderColumn
- [Map<> types ElementCollections](https://github.com/hibernate/hibernate-reactive/issues/532)
- [Embeddable entity with a collection of elements](https://github.com/hibernate/hibernate-reactive/issues/533)
- additional tests for each
See comments on [PR #531](https://github.com/hibernate/hibernate-reactive/pull/531)

[#44] Add support for @ElementCollection

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/DefaultPortTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DatabaseConfiguration.java

Fixes #575 
This also throws an exception now if we don't have a default port for the scheme in the URI.
@gavinking I've noticed we still have the class [UriPoolConfiguration](https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/test/java/org/hibernate/reactive/UriPoolConfiguration.java) around.
I don't think we are using it now and if I remember correctly we plan to use it when they added some changes in Vert.x.
I'm wondering if we should remove it for now or at least add a Javadoc to it.

[#575] Set default port for MariaDB

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/JoinedSubclassIdentityTest.java

A joined subclass should use sequence of superclass when emulating autoincrement columns on postgres.

fix bug #611

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveCollectionLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/SessionUtil.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyManyToOneAssociationTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyOneToManyAssociationWithFetchTest.java

`StatelessSession` in core doesn't do lazy fetching, because with it being transparent, it's just a bit too dangerous.
But with it being a explicit operation in HR, I think it's safe enough to add.

add StatelessSession.fetch()

---

README.md
hibernate-reactive-core/build.gradle

Sometimes I want to run only selected tests on all databases without running the whole suite.
Example:
```
./gradlew testAll [-Pdocker] -PincludeTests=DefaultPortTest 
```
I know that a task of type `Test` supports the `--tests` parameter
but, for some reason, it doesn't work in this case.

Allow filtering of tests with testAll

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java

See discussion #522
Users can now call `.getResultList().onItem().disjoint()`, I believe

remove Mutiny.Query.getResults()

---

.github/workflows/tracking-orm-5.build.yml
.github/workflows/tracking-vertx-3.build.yml

I've just realised I've forgotten to update the tasks in the two workflows for the latest ORM and Vert.x and so they were running the stateful example twice.
Apologies

Fix workflow on GitHub

---

.github/workflows/tracking-orm-5.build.yml

It causes too many errors at the moment because of this commit in ORM: https://github.com/hibernate/hibernate-orm/commit/ed3bbf15e476b064b6a55a80ac0c1570a4287bf0
I think the solution would be to add similar changes to 5.4 but that requires to wait for the another release.
It's easier to disable it for now

Disable build for ORM 5.5 SNAPSHOTS

---

.github/workflows/tracking-orm-5.build.yml

I've just realized that it is possible to disable the job on GitHub, so I've reverted the previous change and
added a comment to the original job.
We can decide later if we want to re-enable it. I will create an issue so that we don't forget.

Better way to disable 5.5 ORM Job

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompletionStagesTest.java

fixes [#547](https://github.com/hibernate/hibernate-reactive/issues/547)
added tests for all `total(..)` methods
added tests for most `loop(...)` methods

Added unit tests for the methods in CompletionStages

---

.github/workflows/tracking-vertx-3.build.yml

We couldn't see the right Vert.x version used because
we were checking the wrong configuration.

Use correct configuration with depenedencyInsight

---

.github/workflows/tracking-vertx-4.build.yml
README.md
build.gradle
hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerElementCollectionForBasicTypeListTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerOneToOneAssociationTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLQueryParameterNamedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLQueryParameterPositionalTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLQueryTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultipleContextTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/ReactiveConnectionPoolTest.java

Fixes #689 
I've updated to Vert.x but I had to disable some tests on Db2 because of https://github.com/eclipse-vertx/vertx-sql-client/issues/920
I will create an issue so that we don't forget to re-enable them when we will upgrade to Vert.x 4.1

689 update to Vert.x 4.0.3

---

.github/workflows/build.yml
build.gradle
publish.gradle
release/build.gradle

Fixes https://github.com/hibernate/hibernate-reactive/issues/704

[#704] Release snapshots using gradle-nexus.publish-plugin

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java

Make sure that queued requests use the right `session` and `entity` args.

proposed fix for #707

---

documentation/src/main/asciidoc/reference/introduction.adoc

improve wording of callout

---

.github/workflows/tracking-vertx-4.build.yml
build.gradle

https://github.com/hibernate/hibernate-reactive/issues/698
https://github.com/hibernate/hibernate-reactive/issues/697

697,698 : Create workflow for testing the latest Vert.x SQL client snapshots and re-enable DB2 tests

---

README.md
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantTest.java

A couple of missing bits for #754

Drop extra Databases and update README 

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantNoResolverTest.java

Fixes #764 
@gavinking shouldn't also be possible for a user to set the tenant for the stateless session?

Multitenancy without CurrentTenantIdentifierResolver

---

tooling/jbang/Example.java
tooling/jbang/README.md
tooling/jbang/SampleIssueTest.java

targets issue  [#721](https://github.com/hibernate/hibernate-reactive/issues/721)
FIrst pass at a single junit test class that's executable by jbang CLI

single executable jbang-based junit test class

---

.github/workflows/tracking-vertx-4.build.yml

No reason to continue track Vert.x 4.0 if we merge this: https://github.com/hibernate/hibernate-reactive/pull/802

Stop tracking Vert.x 4.0 on CI

---

hibernate-reactive-core/build.gradle
jbang-catalog.json
tooling/jbang/Example.java
tooling/jbang/ReactiveTest.java

I think it's better if one example doesn't require testcontainer, even if it means starting a database manually.
The other example still uses docker.
It also updates assertJ

Updates dependencies for JBang examples

---

jbang-catalog.json
tooling/jbang/Example.java
tooling/jbang/ReactiveTestTemplate.java.qute

With this you just do `jbang init -t reproducer@hibernate/hibernate-reactive mytest`
and you will have a `mytest.java`. 
Advantage is you can create any number of reproducers and you get your own file rather than 
editing the file in jbang's internal cache.
Other fixes:
- move #! at top of file as otherwise it breaks ability to run it directly.
- add simple sl4j to get useful output rather than warnings. you can also use sl4fj-nop if you just want it quite.

Adds jbang template to create reproducers

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveActionQueue.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/Cascade.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveFlushingEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveMergeEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveAbstractCollectionPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveBasicCollectionPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/IntBiFunction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/IntBiPredicate.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompletionStagesTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrphanRemovalTest.java

Fixes #836 
I still need to add a couple of test cases but otherwise the PR is ready for a review:
* It removes the AtomicInteger
* Avoid chaining emtpy CompletionStages when possible
* Avoid InStream
* Avoid casting arrays to Stream
* Avoid iterators where possible

Improve loop performance

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/PreparedStatementAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/TimestampTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/UTCTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesAndCallbacksForAllDBsTest.java

Fixes #856 ... sort of
This is what I would do and it seems consistent to what happens with ORM and MySQL (after a quick test).
I think OffsetTime is the one that's weird, because when we return the value it won't match the original Timezone.

hibernate.jdbc.time_zone support for Time

---

gradle.properties

I've copied the properties we have there so that it make it easier to enable a specific build configuration when working in the IDE.
They are supposed to stay uncommented and only enabled when working locally.

Add and describe build properties in gradle.properties

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultilineImportsTest.java

I've removed the field of type `TEXT` because it's not supported
by all databases and the table is created by Hibernate Reactive
anyway, and it doesn't affect the test

Fix MultilineImportsTest for all dbs

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveEntityManagerFactoryBuilder.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSessionFactoryBuilderService.java

Attempt to fix #877.
WDYT @DavideD?

fix JDBC batching

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java

I think this version is more consistent with the other tests.
I also prefer, if possible,  to not have places where we ignore the returned value of `closeSession` (although in this case it was correct).

[#877] Refactor tests for batching connection

---

.github/workflows/build.yml

Because JDK 18  ea4 is no longer available for download.

Upgrade JDK 18 tests to JDK 18+ea9

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/UTCTest.java

Fixes [#901](https://github.com/hibernate/hibernate-reactive/issues/901)

[#901] removed failing assertion

---

.github/workflows/tracking-orm-5.build.yml
gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/BatchingConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ProxyConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/AbstractReactiveInformationSchemaBasedExtractorImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/MySqlReactiveInformationExtractorImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcConnectionProviderInitiator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcMultiTenantConnectionProviderInitiator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/PostgreSqlReactiveInformationExtractorImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveImprovedExtractionContextImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSchemaManagementTool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSchemaManagementToolInitiator.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SchemaUpdateCockroachDBTestBase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SchemaUpdateMariaDBTestBase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SchemaUpdateMySqlTestBase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SchemaUpdatePostgreSqlTestBase.java

For https://github.com/hibernate/hibernate-reactive/issues/536, https://github.com/hibernate/hibernate-reactive/issues/913, and https://github.com/hibernate/hibernate-reactive/issues/910 .
Requires ORM PR:
https://github.com/hibernate/hibernate-orm/pull/4106

[536] [913] [910] SchemaMigrator/SchemaValidator support for PostgreSQL and CockroachDB

---

.github/workflows/tracking-orm-5.build.yml

The purpose of the build with 5 is to track the latest available ORM 5 (that's why it was an interval). Any particular reason for it to be set to 5.6.0.Beta1? I'm assuming @gbadner needed that version while working on the schema issue.
@Sanne Do we care about other minors (like 5.5.x or 5.4.x)?

Track latest available ORM 5.6.x

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/EntityTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveMergeEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveResultSetProcessor.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ManyToOneMergeTest.java

fixes #951
Well, it fixes *one* overloaded version of `DefaultReactiveMergeEventListener.copyValues()`, which was enough to make the given test pass. I'm not sure if the same change needs to be made to the other one.

fix a bug in merge()

---

hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/async/impl/AsyncCloseable.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/async/impl/AsyncIterator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/async/impl/AsyncIterators.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/async/impl/AsyncTrampoline.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/async/impl/Either.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/async/impl/package-info.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java

#964
I've copied the classes we need and made some changes to reuse some methods already in `CompletionStages` (instead of copying additional classes from the library).
Considering that I've copied classes from a library licensed under Apache 2.0,
is there something specific I need to pay attention to when I copy the files?

Remove IBM asyncutil library

---

README.md
build.gradle
gradle.properties
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Upgrade to Vert.x 4.1.4

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java

From integration code, I need to be able to unwrap `Stage.SessionFactory` and `Mutiny.SessionFactory` instances to access the serviceregistry and the `SessionFactoryImpl` delegate.

Introduce an unwrap() capability on the reactive SessionFactory implementations

---

README.md
build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/AbstractReactiveInformationSchemaBasedExtractorImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveImprovedExtractionContextImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSchemaManagementTool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/SqlServerReactiveInformationExtractorImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultilineImportsTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SchemaUpdateSqlServerNoSequenceTestBase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SchemaUpdateSqlServerTestBase.java
podman.md

Fixes #912 
A test for the following pr: https://github.com/hibernate/hibernate-reactive/pull/967
I've rebased it to the latest changes and it's using the available HIbernate ORM (5.6.0.Beta2)
Waiting for [this PR](https://github.com/hibernate/hibernate-orm/pull/4235) to be merged and released

MSSQL Schema update and validation

---

README.md

We will continue to test with Java 8 for the time being
but at least we don't commit to it for the future.
And we are aligned to the base version used by the products.
Fixes #969
I will update the website before the release

Switch from Java 8 to Java 11 in the README

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/spi/Implementor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java

New interfaces that will make it easier for integrators
to access internal components. Similar to the SessionFactoryImplementor
interface in ORM.
@Sanne, we will have to update this line in Quarkus: https://github.com/DavideD/quarkus/blob/07c1037c07ace8b93dcb7a3f06ead6a35da965eb/extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java#L30

Create Implementor interface

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/EntityTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerUniqueKeyTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyUniqueKeyTest.java

This code was disabled because the needed operations in Hibernate ORM were
not exposed.
fixes #959

uncomment code in EntityTypes

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ExternalSqlClientPool.java

It shoudldn't be necessary and it is causing issues
with Quarkus when using schema update/validation
Fixes #1062

Remove check in ExternalSqlClientPool

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveIdentityGenerator.java

I know, the 80s were fun, but it's time to move on...

SQL keywords should always be lowercase

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java

Revise the Hibernate Reactive startup message. Currently it shows
```
INFO  [or.hi.re.pr.im.ReactiveIntegrator] (JPA Startup Thread: default-reactive) HR000001: Hibernate Reactive Preview
```
As HR is now past 1.0, it isn't really preview anymore.

Revise startup message

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java

Relates to https://github.com/quarkusio/quarkus/issues/22433 and #1073
@DavideD

[Draft] to fix "java.lang.IllegalStateException: Session/EntityManager is closed"

---

integration-tests/verticle-postgres-it/LICENSE
integration-tests/verticle-postgres-it/build.gradle
integration-tests/verticle-postgres-it/spotless.license.java
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/Product.java
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/ProductVerticle.java
integration-tests/verticle-postgres-it/src/main/resources/log4j2.properties
integration-tests/verticle-postgres-it/src/test/java/org/hibernate/reactive/it/LocalContextTest.java
settings.gradle

With a test to check the creation of multiple sessions
from different http requests
This is a draft because it doesn't contain the fix already  in main because I want to see that it fails

Add integration-tests module

---

hibernate-reactive-core/build.gradle
integration-tests/verticle-postgres-it/build.gradle

Aligning with latest in Quarkus and ORM core.
We should probably declare a centralized "libraries" section, but won't do that today.

Upgrade to JBoss Logging 3.4.3.Final

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/vertx/impl/DefaultVertxInstance.java

Fixes #1134 
* If not detected:
`[INFO] HR000002: Vert.x not detected, creating a new instance`
* if detected:
`[DEBUG] Vert.x instance detected`

Add log message about Vert.x at start up

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/UnicodeCharsTest.java

@gavinking Is this is correct or there is something I'm missing?

Disable use of Nationalized chars for MariaDb

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/UnicodeCharsTest.java

Fixes #1158
One of the chars used in the test is not compatible with the
collation used when setting the property to true for MySQL or
MariaDB.

Fix UnicodeCharsTest

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveAbstractCollectionPersister.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java

It seems the problem on CI was that the test time out was too short when using Db2. This was causing the first test to fail and some other tests after it even if the database was started (not sure why).
This PR contains:
* Increase timeout for the tests and switch to a class rule (this is what fixed the build on CI)
* Upgrade Db2 to 11.5.7.0
* Print the start up console of Db2 when using docker
* Fix a debug message (it was expecting two parameters but there was only one)

Fix Db2 build failure on CI 

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/InternalStateAssertions.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java

Sometime two different threads can have the same name

Print thread ids when internal assertion fails

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/SequenceGeneratorTest.java

We don't have the permissions for the creation of a new schema with Oracle but one is created anyway when a user is created.
I think it's goog enough for testing for now

Enable SequenceGeneratorDefaultSchemaTest for Oracle

---

README.md
build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveActionQueue.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityInsertAction.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/NonNullableManyToOneTest.java

Rebased https://github.com/hibernate/hibernate-reactive/pull/1174
and upgrade ORM to 5.6.7.Final 
Fix #1077
Fix #1242

ORM 5.6.7.Final and Fix for non nullable associations

---

.github/workflows/build.yml

Fix failures when publishing the docs on hibernate.org
It seems that the main issue is that I have to specify the user name and email.
I've used `hibernate` and `hibernate@users.noreply.github.com` and everything seems to work fine.
Sorry, it seems that when I've tested the changes  to the release, I've messed up somewhere.

Configure hibernate git user and email in the workflow

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/UTCTest.java

When I refactor the code I've delete the configuration without noticing that it sets some properties.
The test didn't fail for me because the time zone matches, I guess

Restore correct configuration for UTCTest

---

.github/workflows/build.yml

See https://inside.java/2022/03/11/setup-java/
Major gain: we won't need to update the download links anymore :)

Move to oracle-actions/setup-java to install newer JDKs

---

README.md
build.gradle

Changelog:
- https://hibernate.atlassian.net/issues/?jql=project%20%3D%2010031%20AND%20fixVersion%20%3D%2032056%20ORDER%20BY%20priority%20DESC%2C%20key%20ASC
In particular see https://hibernate.atlassian.net/browse/HHH-15147 : metamodel gen should work fine on the examples now even in "Jakarta mode"

Upgrade to Hibernate ORM 5.6.8.Final

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DockerImage.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/OracleDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/TestableDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/VertxMariaContainer.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/VertxMySqlContainer.java

@Sanne I've tested this code with a fresh Fedora installation and only using Podman. It seems to work fine for me, except Db2 that starts but doesn't seem to work with Podman. But I think this is a known issue.

Refactoring of the code that starts the containers for testing

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/async/impl/AsyncIterator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/async/impl/AsyncIterators.java

Since it's hard to deal correctly with "thenComposeAsync" operations w/o violating our threading assumptions, I'm going to remove some instances in which we use these.
In particular I found some dead code here; seems these can be trivially deleted.

Cleanup async iterators

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/CachedQueryResultsGenerateStatisticsTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CachedQueryResultsTest.java

addresses [#1015]
After the upgrades to ORM, I revisited this issue.  Verified that the original failing test works (`testQueryPlanCacheHits()`) with `Settings.GENERATE_STATISTICS` to TRUE

Added test to verify query plan cache hits

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/NoVertxContextTest.java

This way it will also work for Oracle and it will be faster.
This test was failing on CI with just one entry, so it shouldn't
make much difference if we test it with 100 or 1000.

Reduce number of entries for NoVertxContextTest

---

README.md

After Vert.x 4.3.1, the limitations we mention for Oracle
have been solved
Fix #1317

Update limitations in the README

---

README.md
hibernate-reactive-core/src/test/java/org/hibernate/reactive/UUIDGeneratorTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/LobTypeTest.java

The latest Vert.x SQL client solves a couple of issues:
* Searching the UUID in Oracle
* Storing `@Lob` for MSSQL
I've also updated the limitations for Db2 (`@Lob` doesn't work)

Enable tests for MSSQL and Oracle

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/IdentifierGenerationTypeTest.java

Addresses #1345 
`IdentifierGenerationTypeTest` is failing for DB2 due to a bug introduced in recent change to vertx-db2-client
Roll back this change when vertx [#899](https://github.com/eclipse-vertx/vertx-sql-client/issues/899) is fixed.

[#1345] Temporarily disable IdentifierGenerationTypeTest for DB2

---

.github/workflows/build.yml

Test against JDK 20 (early access)

---

examples/session-example/src/main/java/org/hibernate/reactive/example/session/Book.java
examples/session-example/src/main/java/org/hibernate/reactive/example/session/MutinyMain.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java

Fix #1386 
I've followed [the approach used by Hibernate ORM](https://github.com/hibernate/hibernate-orm/blob/1350c713a3c271d869d05fdf9e28fe2e57a4e25f/hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java#L1267).
If I'm not mistaken, we are loading all the lazy properties as soon as we load the first one. Is this the correct behaviour?
Shouldn't we just load the lazy field required by the user?

Lazy field

---

.github/workflows/build.yml
.github/workflows/tracking-orm-5.build.yml
.github/workflows/tracking-vertx-4.build.yml
README.md
hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/StartVerticle.java
podman.md
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Fix #1406 
~~This is a draft because I'm waiting for the latest mysql connector to be available on Maven central~~
Nevermind, the problem was that the GAV for the connector have changed: https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-31.html
@Sanne Could you have a quick look and let me know if it's better if we test with different versions, please? Thanks

Upgrade db versions for testing

---

documentation/src/main/asciidoc/reference/introduction.adoc

futher explanation of "field-level lazy"

---

build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
integration-tests/bytecode-enhancements-it/README.md
integration-tests/bytecode-enhancements-it/build.gradle
integration-tests/bytecode-enhancements-it/spotless.license.java
integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/Crew.java
integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/lazytoone/Captain.java
integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/lazytoone/Ship.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/LazyBasicFieldTest.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/LazyOneToOneBETest.java
integration-tests/bytecode-enhancements-it/src/test/resources/log4j2.properties
integration-tests/verticle-postgres-it/build.gradle
settings.gradle

Fix #1417 
This should make it possible [to fix the related issue on Quarkus](https://github.com/quarkusio/quarkus/issues/28975).
I've decided to add an additional module to the project to test with bytecode enhancements. Hopefully, in the future we will have something better, but it beats not having tests. I've heard Hibernate ORM has some nice utilities for this.
Not sure how we didn't notice before, but the problem was that in this particular scenario we run a query that returns a CompletionStage and we try to assign it to one of the field. Instead we need to assign the result when it's ready.

Fix lazy one to one with bytecode enhancements

---

README.md
build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/EntityTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEntityEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveMergeEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryExecutorLookup.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java

Also requires an upgrade to Hibernate ORM 5.6.14.Final (upgrade included)

Improved patch to prevent type cache pollution on getting ReactiveQueryExecutor

---

.github/workflows/build.yml

JDK 18 EOL'd on 2022-09-20
See https://endoflife.date/java

Test Hibernate Reactive against JDK 21 EA, JDK 19 GA

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/UTCTest.java

removed first assertion check in UTCTest.testOffsetTime()

fix UTCTest: PostgreSQL results: FAILURE (804 tests, 610 passed, 156 failed, 38 skipped)

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/IdentityGeneratorTypeTest.java

Simply remove the entity that uses a short type as an id because it conflicts with [this](https://github.com/hibernate/hibernate-orm/blob/6.2.0.CR1/hibernate-core/src/main/java/org/hibernate/dialect/identity/PostgreSQLIdentityColumnSupport.java#L37).

Fix IdentityGeneratorTypeTest

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/SubselectFetchTest.java

As mentioned in [HHH-16136](https://hibernate.atlassian.net/browse/HHH-16136), property access worked by chance in ORM 5, but no longer does in 6, so we update the test to use getter access
See also [this](https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/ORM6.20proxy.20issue) Zulip discussion.

Fix SubselectFetchTest

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinyExceptionsTest.java

Hibernate ORM no longer wraps `HibernateException`
in a `PersistenceException`, as per [HHH-15797](https://hibernate.atlassian.net/browse/HHH-15797)

Fix MutinyExceptionsTest

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/iternal/ReactiveSimpleInsertQueryPlan.java

This is done by following same pattern used in the other *QueryPlan classes: make a reactive copy of the ORM implementations
With this change HQLUpdateQueryTest now passes and no new failures occur

Fix HQLUpdateQueryTest

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/ReactiveCacheEntityLoaderHelper.java

This is done by following same pattern that we have in main: essentially make a reactive copy of the CacheEntityLoaderHelper (which exists in main but was deleted to make the project compile against ORM 6)
With this change `org.hibernate.reactive.LockOnUpdateTest` passes and there are no new failures

Fix LockOnUpdateTest

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/ResultsCheckerUtil.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/env/internal/ReactiveMutationExecutor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/mutation/internal/ReactiveMutationExecutorSingleBatched.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/mutation/internal/ReactiveMutationExecutorStandard.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchingConnectionTest.java

This change leverages the fact that when batching
is enabled, a BatchingConnection is provided
under the hood that takes care of all the necessary plumbing.
Before the change, **122** tests where failing, after this change the number drops to **87**

Introduce batch single table batch support

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyPropertyTest.java

This test also fails with plain old ORM 6:
```java
package org.hibernate.reactive;
import jakarta.persistence.Basic;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.metamodel.Attribute;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.hibernate.Hibernate;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor;
import org.hibernate.cfg.Configuration;
import org.hibernate.dialect.PostgreSQLDialect;
import …
```

Disable LazyPropertyTest

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/EmulatedSequenceReactiveIdentifierGenerator.java

This avoid EmulatedSequenceReactiveIdentifierGenerator to fail to initialize: `renderedTableName` is already correctly initialized by the call to `super#configure`

Fix initialization of EmulatedSequenceReactiveIdentifierGenerator

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java

This results in the failing tests going from `74` to `67`

Properly pass input parameters in ReactiveJoinedSubclassEntityPersister#deleteReactive

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NativeParametersRendering.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/PostgreSQLParameterRenderer.java

It turns out we can't get rid of the `Parameters` approach to avoid post-processing of SQL statements, but there's some progress.
This avoids some post-processing of the SQL generated by ORM core; it takes care of the PostgreSQL specific parameters format; not applicable yet for mutation operations.

Introduce a NativeParametersRendering service to directly render PostgreSQL-compatible SELECT statements

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/CachedQueryResultsGenerateStatisticsTest.java

Hibernate ORM statistics test don't test Criteria queries (which don't seem to update statistics) and they also only test the statistics for query creation, not query execution

Update CachedQueryResultsGenerateStatisticsTest to match ORM tests

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/spi/ReactiveAbstractSelectionQuery.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java

Thrown exceptions were being properly routed through the "convertException" utilities, but when it's wrapped in a CompletionException we'd fail to recognize it.

Ensure we apply the exception converter consistently

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/services/ServiceInitiatorsTest.java

Adding just some comments and an integration test that would trigger if there's new services defined in ORM
which we should define too.
The will also print out some useful reports about what exactly we're overriding.

Making it somewhat easier to manage difference with ORM among Service Initiators

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/StandardReactiveJdbcMutationExecutor.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/PersistThenDeleteTest.java

Fixing auto-flush on mutation queries

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/LazyBasicFieldTest.java

It works after the changes we made to fix the examples

[#1516] Reenable LazyBasicFieldTest#testFetchBasicField

---

.github/workflows/build.yml
build.gradle
examples/native-sql-example/build.gradle
examples/session-example/build.gradle
gradle.properties
integration-tests/bytecode-enhancements-it/build.gradle

This also changes to sonatype link to: https://oss.sonatype.org/content/repositories/snapshots/

Enable ci tests using latest Hibernate snapshots

---

.github/workflows/build.yml
hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/insert/ReactiveAbstractReturningDelegate.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/UTCTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/OracleDatabase.java

Fix https://github.com/hibernate/hibernate-reactive/issues/1532
I disabled UTCTest for Oracle due to 4 test failures.
* testDate()
* testCalendar()
*  testLocalDateTime()
* testZonedDateTime() 
Example:
```
throws jakarta.persistence.NoResultException: No result found for query [from ThingInUTC where date=:dt]
//	     at app//org.hibernate.reactive.query.spi.ReactiveAbstractSelectionQuery.reactiveSingleResult(ReactiveAbstractSelectionQuery.java:175)
```

Add Oracle

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java

Fix #1565
Log example:
```
INFO DefaultSqlClientPoolConfiguration [vert.x-worker-thread-0] HR000025: Connection pool size: 5
INFO DefaultSqlClientPool [vert.x-worker-thread-0] HR000013: Detected driver [io.vertx.pgclient.spi.PgDriver] 
INFO DefaultSqlClientPool [vert.x-worker-thread-0] HR000013: Detected driver [io.vertx.mysqlclient.spi.MySQLDriver] ✓
```

Add check mark in front of the selected driver

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveCollectionRemoveAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityDeleteAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityIdentityInsertAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityRegularInsertAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityUpdateAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveFlushingEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveAutoFlushEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEntityEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveInitializeCollectionEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLockEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveMergeEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactivePersistEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactivePostLoadEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveRefreshEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveResolveNaturalIdEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java

Sync listeners and actions with changes in H6.

update DefaultReactiveListeners and Actions

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/testing/ReactiveAssertions.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/AutoZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/ColumnZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/DefaultZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/JDBCTimeZoneZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/PassThruZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/UTCNormalizedInstantTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/UTCNormalizedZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/BasicTypesAndCallbacksForAllDBsTest.java

Additional tests for Instant and temporal types with offset
Fix #1584

Timezone tests with new assertions

---

podman.md

Add registry to docker commands in podman.md

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnectionPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ExternalSqlClientPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinyExceptionsTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveConstraintViolationTest.java

There were some conflicts with the changes I made for the autodetection of the version of the dialect.
I had to add a couple of methods to `ReactiveConnectionPool` because the default `SqlExceptionHelper` needs a dialect and we don't have the dialect during yet when we create the connection to check the version on the database.
Because it uses the latest ORM, we don't need to skip the test for SqlServer anymore.
Fix #1602

Wire in SqlExceptionHelper which is now useful in Vert.x 4.4.0

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveSequenceIdentifierGenerator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedIdentityGenerationTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedInsertionTest.java

This fixes a couple of very tricky bugs with Id generation by our optimisers.
Fixes #1595
Fixes #1587

Identifier generator fix

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmptyCompositeCollectionKeyTest.java

Vert.x SQL client throws:
```
java.lang.IllegalStateException: Needed to have 6 in buffer but only had 0. In JDBC we would normally block here but need to find a non-blocking solution
```

Skip EmptyCompositeCollectionKeyTest for Db2

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedIdentityGenerationTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedInsertionTest.java

Fix #1609 
After the upgrade to Vert.x 4.4.2, these tests work for MSSQL:
* MultithreadedIdentityGenerationTest
* MultithreadedInsertionTest
Because before we couldn't use the correct dialect. See https://github.com/hibernate/hibernate-reactive/issues/1596

Re-enable tests for MSSQL

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java

A micro optimisation - not expecting this to make a significant difference, but it should remove some noise from profiling data, making it easier to analyze.

Stronger guard against trace logging in VertxContext

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/EntityTypes.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerUniqueKeyTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyUniqueKeyTest.java

Follows https://github.com/hibernate/hibernate-reactive/pull/1685
Fix #1504

Fix issue with merge and getReference

---

integration-tests/techempower-postgres-it/build.gradle
integration-tests/techempower-postgres-it/src/main/java/org/hibernate/reactive/it/techempower/VertxServer.java
integration-tests/verticle-postgres-it/build.gradle
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/VertxServer.java

Not everybody has docker installed and we need to make sure that it's still  possible to run the full build when there is a remote database already started.
Fix #1711

Start container only if requested

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleIdEntityLoaderProvidedQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/internal/ReactiveNamedObjectRepositoryImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SQLSelectTest.java

Superseed https://github.com/hibernate/hibernate-reactive/pull/1708
@blafond  I've just added a commit that clean up the test 
Fix #1627

Issue 1627

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/TimeZoneStorageMappingTest.java

[#1442] Test TimeZoneStorage

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/GeneratorValueUtil.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/tuple/MutinyGenerator.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CurrentUser.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySequenceGeneratorTest.java

Fix #1741
@gavinking  Does it make sense? Or am I missing something?
This is the change: https://github.com/hibernate/hibernate-reactive/commit/d8e08d74b35288733bebc211efcc9686ff291d52

Update MutinyGenerator#generate signature

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/SubselectFetchTest.java

The upgrade to Hibernate ORM 6.2.8.Final fixes this issue. See https://hibernate.atlassian.net/browse/HHH-17130
Fix #1502

Re-enable SubselectFetchTest

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchFetchTest.java

#1501 is fixed in Reactive 2.1 (ORM 6.3.0.Final)
* note that `testQuery()` is still disabled in 2.0.5

[#1501] enable BatchFetchTest.testQuery()

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveStandardRowReader.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SubselectFetchTest.java

fixes #1742 
- added one line fix based on changes in ORM [#HHH-16624](https://hibernate.atlassian.net/browse/HHH-16624) in [StandardRowReader.finishUp()](https://github.com/hibernate/hibernate-orm/commit/f8275f1a70d48a6e655fa63e9e69e0055cc88222#)
Tested this change on branch for this [PR](https://github.com/hibernate/hibernate-reactive/pull/1747) and it worked

[#1742] fix error in reactive SubselectFetchTest

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java

@DavideD what is the status of support for batch fetching and subselect fetching? We do support them both now, is that correct?

add new methods from H6.3 to control batch/subselect fetching

---

gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityDeleteAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveDeleteCoordinator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/RowIdUpdateAndDeleteTest.java

Fix #1756 
See https://hibernate.atlassian.net/browse/HHH-17167
Requires https://github.com/hibernate/hibernate-orm/pull/7306 to be merged in Hibernate ORM

RowId ignored during deletes

---

gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityDeleteAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveDeleteCoordinator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/RowIdUpdateTest.java

Reverts hibernate/hibernate-reactive#1762
Sorry, merged by mistake

Revert "RowId ignored during deletes"

---

README.md
build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityDeleteAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveCoordinatorFactory.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveMergeCoordinatorStandardScopeFactory.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveDeleteCoordinator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveMergeCoordinator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/RowIdUpdateAndDeleteTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/UpsertTest.java

Fix #1702 
Requires the latest `main` in Hibernate ORM
Built on top of https://github.com/hibernate/hibernate-reactive/pull/1764 because it fixes some compilation errors
Supersedes #1757:
* It seems to only work for PostgreSQL 
* Implements and add tests for `upsert( String, Object )`
* Minor fixes to some classes
* Fix the test case
* Remove unnecessary classes

Add support for StatelessSession#upsert

---

README.md
build.gradle
gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveDeferredResultSetAccess.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CustomOneToOneStoredProcedureSqlTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CustomStoredProcedureSqlTest.java
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Throw an exception if query doesn't have a result but we expect one

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveDeferredResultSetAccess.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CustomOneToOneStoredProcedureSqlTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CustomStoredProcedureSqlTest.java

Same as https://github.com/hibernate/hibernate-reactive/pull/1797
but for the 2.0 branch
Fix #1792

 Throw an exception if query doesn't have a result but we expect one #1797 

---

.github/workflows/build.yml
README.md
build.gradle
gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityUpdateAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleIdArrayLoadPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleIdLoadPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Upgrade Hibernate ORM to 6.3.2.Final

---

README.md
build.gradle
gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/Cascade.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveFlushingEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveInitializeCollectionEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveRefreshEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ExecutionContextWithSubselectFetchHandler.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveCollectionLoaderSingleKey.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleIdLoadPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/SingleIdExecutionContext.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/metamodel/mapping/internal/ReactiveToOneAttributeMapping.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveDeleteCoordinator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveInsertCoordinator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveUpdateCoordinatorStandard.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcMultiTenantConnectionProvider.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ReactiveSimpleDeleteQueryPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/cte/ReactiveCteInsertHandler.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/spi/ReactiveSelectQueryPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/StandardReactiveSelectExecutor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/ReactiveAbstractEntityInitializer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntityDelayedFetchInitializer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntityJoinedFetchInitializer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchInitializer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveEntityDelayedFetchImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveStandardRowReader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/spi/ReactiveListResultsConsumer.java

Fix #1782 
Requires next Hibernate ORM release

Upgrade orm to 6.4

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/dialect/ReactiveOracleSqlAstTranslator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/dialect/internal/ReactiveStandardDialectResolver.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/mutation/internal/ReactiveMutationExecutorSingleSelfExecuting.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/insert/ReactiveAbstractReturningDelegate.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveMergeCoordinatorStandardScopeFactory.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveMergeCoordinator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveTypeContributor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/StandardReactiveJdbcMutationExecutor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/model/ReactiveDeleteOrUpsertOperation.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/model/ReactiveOptionalTableUpdateOperation.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/model/ReactiveSelfExecutingUpdateOperation.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveDeferredResultSetAccess.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/UpsertTest.java

Follows https://github.com/hibernate/hibernate-reactive/pull/1781
Fix #1768

Upsert dbs support

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinyExceptionsTest.java

Test ConstraintViolationException SQLState code

---

hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CancelSignalTest.java

Fix #1436 
Supersedes https://github.com/hibernate/hibernate-reactive/pull/1439

Close connection on cancel signal

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySelectionQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/ReactiveSelectionQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sql/internal/ReactiveNativeQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/ReactiveSqmSelectionQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ReactiveQuerySqmImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ReactiveSqmSelectionQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSelectionQueryImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrderTest.java

Support setOrder

---

README.md
build.gradle
gradle.properties
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JavaTypesArrayTest.java
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Fix #1820
Fix #1821 
Fix #1819

Upgrade Vert.x to 4.5.1 + minor fixes

---

build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactivePostLoadEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/ReactiveAbstractEntityInitializer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchByUniqueKeyInitializer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchInitializer.java

I need to clean it up, but should fix the issues with ORM 6.4.1.Final

Upgrade to ORM 6.4.1.Final

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveMergeCoordinatorStandardScopeFactory.java

Fix #1838 
This code causes a failure with Quarkus at start up: https://github.com/quarkusio/quarkus/issues/38263
CI still works when I remove it, anda `DeleteOrUpsertOperation` cannot be cast to `OptionalTableUpdate` anyway.
So I don't think this code is useful.

Remove unused code that causes error on in Quarkus at start up

---

.github/workflows/tracking-orm-6.build.yml
.github/workflows/tracking-vertx-4.build.yml
README.md
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/VertxServer.java
podman.md
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Fix #1854 
Fix #1853 
Fix #1852 
Fix #1851 
Fix #1850 
Fix #1847

Dependencies and databases upgrade

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/PostgreSqlReactiveInformationExtractorImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/StructComponentTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/StructEmbeddableTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/DB2Database.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MSSQLServerDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/OracleDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/BasicTypesTestEntity.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JavaTypesArrayTest.java

Fix #1641 
Supersedes https://github.com/hibernate/hibernate-reactive/pull/1846
I've just refactored a bit the `JavaTypesArrayTest`.

Tests for @Array and @Struct

---

README.md
build.gradle
hibernate-reactive-core/build.gradle

Fix #1861 and Fix #1863
Note that we need the upgrade to Mutiny 2.6.3 or we will have some race condition caused by https://github.com/smallrye/smallrye-mutiny/issues/1494

Upgrade Hibernate ORM to 6.4.4.Final and Mutiny to 2.6.3

---

build.gradle
gradle.properties

It should be set in the default file and not the gradle.properties
Fix #1888

Fix default Hibernate ORM version setting

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveCoordinatorFactory.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveAbstractDeleteCoordinator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveDeleteCoordinatorSoft.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SoftDeleteTest.java

Fix #1787 
~It's a draft because I think  I've found a bug in ORM and I need to create a test for it~ Never mind, it was just a silly mistake

Add support for `@SoftDelete`

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java
integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/reference/Author.java
integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/reference/Book.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/ReferenceBETest.java

Fix getReference with Bytecode Enhancements

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReferenceTest.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/ReferenceBETest.java

Update javadoc for .fetch + tests

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/BatchingConnection.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/IdentityGenerationWithBatchingTest.java

Fix #1915 
It only happens with identity generation.

Fix NullPointerException whith batching inserts

---

integration-tests/hibernate-validator-postgres-it/build.gradle
integration-tests/hibernate-validator-postgres-it/spotless.license.java
integration-tests/hibernate-validator-postgres-it/src/main/java/org/hibernate/reactive/it/quarkus/qe/database/Author.java
integration-tests/hibernate-validator-postgres-it/src/main/java/org/hibernate/reactive/it/quarkus/qe/database/Book.java
integration-tests/hibernate-validator-postgres-it/src/main/java/org/hibernate/reactive/it/quarkus/qe/database/ISBNConverter.java
integration-tests/hibernate-validator-postgres-it/src/test/java/org/hibernate/reactive/it/quarkus/qe/database/BaseReactiveIT.java
integration-tests/hibernate-validator-postgres-it/src/test/java/org/hibernate/reactive/it/quarkus/qe/database/DatabaseHibernateReactiveTest.java
integration-tests/hibernate-validator-postgres-it/src/test/resources/log4j2.properties
settings.gradle

Hibernate Validator integration test

---

build.gradle
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Upgrade Testcontainers to 1.19.8

---

README.md
build.gradle
gradle.properties

Upgrade Hibernate ORM to 6.5.2.Final

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/BatchingConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnectionPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/ExternalSqlClientPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveImprovedExtractionContextImpl.java
hibernate-reactive-core/src/test/resources/log4j2.properties

Fix #1909
I'm not sure if it strictly necessary anymore to run the queries outside of the current transaction, but I think this way the code is simpler and consistent to what we were doing before. And the code is cleaner.
Basically, I moved the method we used to run the query in the pool.

Avoid creation of multiple connections during schema migration

---

.github/workflows/tracking-orm-6.build.yml
.github/workflows/tracking-vertx-4.build.yml
README.md
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MariaDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java
integration-tests/hibernate-validator-postgres-it/src/test/java/org/hibernate/reactive/it/quarkus/qe/database/BaseReactiveIT.java
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/VertxServer.java
podman.md
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Upgrade dbs version for testing

---

.github/workflows/build.yml

fixes https://github.com/hibernate/hibernate-reactive/issues/1938
Hey @DavideD 😃 
I thought while I was at it (adding JDK builds to other projects) I'd create one for Reactive as well 😃 
22 is now GA, so I've removed the -ea from the version

Add jdk 24 to the build on CI

---

.github/workflows/build.yml

Additional fixes for #1935 I missed

Update dbs for testing examples on CI

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLockEventListener.java

Make DefautlReactiveLockEventListener#cascadeLock reactive

---

README.md
build.gradle
gradle.properties
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Fix #1927
This is technically ready, but we should wait for the quarkus upgrade before merging it

Upgrade Vert.x SQL client to 4.5.8

---

hibernate-reactive-core/src/test/resources/log4j2.properties
integration-tests/bytecode-enhancements-it/src/test/resources/log4j2.properties
integration-tests/hibernate-validator-postgres-it/src/test/resources/log4j2.properties
integration-tests/verticle-postgres-it/src/main/resources/log4j2.properties

Fix #1950 
* Print the full class path with the line number this way the IDE can link the message to the corresponding class
* Disable log related to the connection: it's useful only in certain situations and too verbose otherwise
* Uniform all log configurations in the different modules

Change log4j.properties

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompositeIdTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EagerUniqueKeyTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyReplaceOrphanedEntityTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrderedOneToManyTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/OrphanRemovalTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReferenceTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/SubselectElementCollectionForEmbeddableTypeListTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JoinColumnsTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JsonTypeTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/StringToJsonTypeTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/UserJsonTypeTest.java

Some refactoring of existing tests and I made some improvements to OrphanRemovalTest
Fix #1952 
----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt).
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-reactive/blob/main/LICENSE).
----------------------

Tests clean up

---

.github/workflows/build.yml

Snapshot builds tend to fail quite often and sometimes we cannot even fix an issue until another project has been released.
I moved the build testing the snapshots under the branches `wip/*`. This way the failure of a build using snapshots won't affect the release of stable versions.
[Snapshot builds are here](https://github.com/hibernate/hibernate-reactive/branches).

Remove snapshots releases from main branch

---

build.gradle
gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveDeferredResultSetAccess.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertyJoinedTableTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertySingleTableTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertyUnionSubclassesTest.java
integration-tests/bytecode-enhancements-it/src/main/java/org/hibernate/reactive/it/lazytoone/Ship.java

Fixed compile errors.  Allowing PR checks to verify tests.

ORM 7.0.0.Beta1

---

.github/workflows/build.yml
.github/workflows/scheduler.yml

Schedule snapshots build

---

.github/workflows/build.yml
.gitignore
build.gradle
ci/release/Jenkinsfile
publish.gradle
release/build.gradle
settings.gradle

Part of #1956 
- remove the JBoss Nexus repository from the configuration
- remove release jobs from the GitHub workflow
- add a first draft of the Jenkins pipeline
@yrodiere Maybe you want to have a quick look? It mimics the one pipeline in ORM, but I'm not updating the website and not using the JIRA. Basically, I've tried to keep the changes to the existing release task to a minimum.
I will improve everything when we have tested that it actually works with a real release.

Remove release from GitHub

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/metamodel/mapping/internal/ReactiveEmbeddedIdentifierMappingImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractPersisterDelegate.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableInitializerImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java

Fix support for @EmbeddedId

---

build.gradle
ci/release/Jenkinsfile
ci/snapshot-publish.Jenkinsfile
documentation/build.gradle
gradle.properties
local-build-plugins/build.gradle
local-build-plugins/settings.gradle
local-build-plugins/src/main/java/org/hibernate/reactive/env/ProjectVersion.java
local-build-plugins/src/main/java/org/hibernate/reactive/env/VersionsPlugin.java
release/build.gradle
settings.gradle

Fix #1956 
This should fix the release process via Jenkins... we will know for sure next time we release

Update release process

---

README.md
build.gradle
gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveIdentifierGeneratorFactory.java
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Fix #1992 
Fix #1993 
Hibernate ORM to 6.6.1.Final
Vert.x to 4.5.10

Upgrade Hibernate ORM and Vert.x

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/ResultSetAdaptor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveTypeContributor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/type/descriptor/jdbc/ReactiveJsonJdbcType.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JsonQueryTest.java

Fix queries on JSON fields

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveNonAggregatedIdentifierMappingFetch.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ManyToOneLazyIdClassTest.java

IdClass with ManyToOne

---

.github/workflows/build.yml

Fix #2008 
Copied the Cache configuration from the ORM build

Update GitHub build cache configuration

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java

This was already added to ORM SS in 6.6. See #2040.

add StatelessSession.getIdentifier() because repositories need it

---

.github/workflows/build.yml

Fix #2044 
Include 2.* and 3.* branches and tags (before it was only the WIP ones)

Enable GitHub workflows on different branches

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java

see https://github.com/hibernate/hibernate-reactive/issues/2042

#2042 add insertMultiple() and friends, with semantics aligned with ORM7

---

build.gradle
ci/release/Jenkinsfile
ci/snapshot-publish.Jenkinsfile
publish.gradle

[#1095] Sign the artifacts for Sonatype
[#2027] Use env-vars for passing secrets used during release
NOTE : ready for review, but draft as we need to coordinate changes in [hibernate-release-scripts](https://github.com/hibernate/hibernate-release-scripts/pull/26)

Signing + env-vars

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveNonAggregatedIdentifierMappingInitializer.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ManyToOneIdClassTest.java

Fix #2007 
Follows https://github.com/hibernate/hibernate-reactive/pull/2057
I've just added some minor clean-ups and switch the order of the commits so that the new test is added after the fix (in case we have to run a bisect).
@dreab8 Can you have a look and let me know if it makes sense? Thanks

Null pointer when using IdClass

---

ci/compare-build-results.sh
ci/nightly/Jenkinsfile
hibernate-reactive-core/build.gradle

fixes https://github.com/hibernate/hibernate-reactive/issues/1929
Hey @DavideD  😃,
I thought while I was at it for ORM, I might as well see about Reactive....
It seems that the only thing for Reactive was to enable those two bool flags as nothing else was detected by the check. Now as for the check to make sure we don't break something along the way ... for Search/Validator and ORM I've added a check in the nightly builds, not sure about Reactive as most of the things are done with GH actions here... How would you want to handle that? (A Validator example https://ci.hibernate.org/blue/organizations/jenkins/hibernate-validator-nightly/detail/main/46/pipeline)
Also... to double check... Reactive produces only one jar (`hibernate-reactive-core`), right? Here's the result I get from the …

Enable reproducible archives

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableForeignKeyResultImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdWithManyTest.java

Fix https://github.com/hibernate/hibernate-reactive/issues/2060
Related Jira https://issues.redhat.com/browse/HREACT-65

ClassCastException when using embeddable ids

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CollectionTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/EntityTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableForeignKeyResultImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdWithManyTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToManyArrayMergeTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToManyMapMergeTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/OneToManyMergeTest.java

Backports changes in main to 2.4

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdWithManyTest.java

Some additional assertions for the test introduced with #2060

Add assertions to the test

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/AutoZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/ColumnZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/DefaultZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/JDBCTimeZoneZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/PassThruZonedTest.java

Fix: https://github.com/hibernate/hibernate-reactive/issues/1724
Related: https://issues.redhat.com/browse/HREACT-56

 Attempt to fix JDBCTimeZoneZonedTest sporadic failures probably due lack of database Timestamp precision

---

examples/native-sql-example/src/main/resources/META-INF/persistence.xml
examples/session-example/src/main/resources/META-INF/persistence.xml
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSelectionQueryImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/AutoZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/ColumnZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/DefaultZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/JDBCTimeZoneZonedTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/PassThruZonedTest.java

Backport fixes for test related to time zones

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/mutation/ReactiveUpdateRowsCoordinatorOneToMany.java

Don't ignore return value of deleteRows

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQueryProducer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CriteriaMutationQueryTest.java

Fix for https://github.com/hibernate/hibernate-reactive/issues/1885

Add createMutationQuery method that accept criterias

---

.github/workflows/build.yml

Backport #2097 for 2.4
PR:  https://github.com/hibernate/hibernate-reactive/pull/2098
@marko-bekhta, could you double check that I didn't do anything stupid, please?

[2.4] Use SHA instead of versions in GH actions 

---

hibernate-reactive-core/src/main/java/org/hibernate/engine/internal/ReactivePersistenceContextAdapter.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveCallbackImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveNaturalIdLoaderDelegate.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleIdLoadPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleUniqueKeyEntityLoaderStandard.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/spi/ReactiveAfterLoadAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/spi/ReactiveAbstractSelectionQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sql/internal/ReactiveNativeQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ReactiveQuerySqmImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ReactiveSqmSelectionQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveDeferredResultSetAccess.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/spi/ReactiveListResultsConsumer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/spi/ReactiveSingleResultConsumer.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/FindByIdWithLockTest.java

Fix #1905 
Supersedes https://github.com/hibernate/hibernate-reactive/pull/2117
@dreab8, I applied the changes we discussed, could yuo double check I didn't miss anything, please?
Thanks

Fix exception when using find with lock

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyInitializationExceptionTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessProxyUpdateTest.java

Fix #1514
@Sanne, In case you want to see what the error was

Hardening transaction state

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinyStatelessSessionTest.java

and add missing overloads of `Mutiny.StatelessSession.createQuery()`
Fix #2122.
Also add tests for `Mutiny.StatelessSession` which were missing

add StatelessSession.get() accepting multiple ids

---

README.md

fixes https://github.com/hibernate/hibernate-reactive/issues/2134

 Add Reproducible Central badge

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/ReactiveStatelessDefaultBatchSizeTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchingConnectionTest.java

Fix https://github.com/hibernate/hibernate-reactive/issues/2108

StatelessSession insertAll in batch does not do batching

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/temptable/ReactiveGlobalTemporaryTableStrategy.java

Quarkus doesn't like it when running in native mode
Fix #2150

Avoid creation of logger at runtime

---

gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveEntityBatchLoaderArrayParam.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveMultiIdEntityLoaderArrayParam.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/ReactiveQueryImplementor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sql/internal/ReactiveNativeQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ReactiveSimpleDeleteQueryPlan.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQueryProducer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessWithBatchTest.java

Upgrade Hibernate ORM to 3.0.0.Beta5

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java

Closes #2174
Local context data management methods are deprecated and will be removed in Vert.x 5.
This change will make it easier to upgrade to Vert.x 5 (should be just a matter of changing imports)

Prepare for Vert.x 5 upgrade in Vert.x Context

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/ContextualDataStorage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java
hibernate-reactive-core/src/main/resources/META-INF/services/io.vertx.core.spi.VertxServiceProvider

Closes #2176
In Vert.x 5, the local context data map is deprecated.
Hibernate Reactive can have its own Vert.x contextual data storage (requires creating a io.vertx.core.spi.context.storage.ContextLocal key).

Create custom Vert.x contextual data storage

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/temptable/ReactiveGlobalTemporaryTableStrategy.java

[2.4] Avoid creation of log at runtime

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableInitializerImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchInitializer.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdWithManyEagerTest.java

fixes https://github.com/hibernate/hibernate-reactive/issues/2166

Backport to 2.4 of [#2166] Hibernate Reactive eager fetching the wrong record for ManyToOne 

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/UTCNormalizedZonedTest.java

This should prevent the failures we sometimes have on CI.
Fix #2187

Use adjustToDefaultPrecision in UTCNormalizedZonedTest

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/timezones/UTCNormalizedZonedTest.java

Replace `DateTimeUtils.roundToDefaultPrecision` with `DateTimeUtils.adjustToDefaultPrecision`
This should prevent the failures we sometimes have on CI.
Backport #2187 for 2.4

[2.4] Backport "Use adjustToDefaultPrecision in UTCNormalizedZonedTest"

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessWithBatchTest.java

Fix error chaining stages in ReactiveStatelessWithBatchTest

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveDeleteEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLockEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveRefreshEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/cte/ReactiveAbstractCteMutationHandler.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/mutation/internal/cte/ReactiveCteInsertHandler.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntityInitializerImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/entity/internal/ReactiveEntitySelectFetchInitializer.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinyStatelessSessionTest.java

Backports #2209 to 2.4
Superseeds #2211
I've just rewrote one commit message, it was referring to the wrong issue

[2.4] CCE in simple criteria query with StatelessSession due to cast to ReactiveSession

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/ContextualDataStorage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java

Fix #2207 
We store the session in the Vert.x local context.
But, Quarkus needs a way to access the same context when using Panache.
See quarkus issue: https://github.com/quarkusio/quarkus/issues/47314

Provide access to the contextual data map

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/util/impl/CompletionStages.java

Fix #2181
Mainly a first draft that I think it's reasonable to release for now.
But, the ReactiveSessionImpl needs more work. I will continue to look into it,
but I don't want to delay the Hibernate ORM release.
Merge after https://github.com/hibernate/hibernate-reactive/pull/2221

Align the session to the latest changes in ORM 7

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveUpdateCoordinatorStandard.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/TimestampTest.java

fixes https://github.com/hibernate/hibernate-reactive/issues/2138
I've added the test as disabled, as we'd need an ORM release that fixes https://hibernate.atlassian.net/browse/HHH-19306 first

Use UPDATE event type for generator where applicable

---

.gitignore
.release/.gitignore
build.gradle
ci/release/Jenkinsfile
ci/snapshot-publish.Jenkinsfile
jreleaser.yml
publish.gradle
release/build.gradle

Fixes https://github.com/hibernate/hibernate-reactive/issues/2222
This one is to match the ORM updates: https://github.com/hibernate/hibernate-orm/commit/ec026fc7fbd9a9ec45b4602e6294234f47f9d649

Add a simple JReleaser configuration

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java

It should have been "proxies".
But anyway I rewrote the sentence.

fix misspelling in Javadoc

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQueryProducer.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java

A first draft of the shared session contract. I've basically collected the methods we already have in both sessions.
See Mutiny.SharedSessionContract (or Stage.SharedSessionContract).
Personally, I like knowing which methods are not specific to a session.

Shared session contract

---

hibernate-reactive-core/src/main/java/org/hibernate/engine/internal/ReactivePersistenceContextAdapter.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CollectionTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/EntityTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/spi/ReactiveSharedSessionContractImplementor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveInitializeCollectionEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/UpsertTest.java

1. fix some more incorrect casts to ReactiveSession or ReactiveSessionImpl
2. remove the SS.upsert() method taking an entity name (we don't need it)
3. some minor code cleanups in EntityTypes and CollectionTypes

fixes before release

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/CollectionTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/EntityTypes.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityInsertAction.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSession.java

To make sure things don't break in StatelessSessions.

generalize uses of SessionImplementor to SharedSessionContractImplementor

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionFactoryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionFactoryImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/MutinySessionTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java

This will make it easier to implement the necessary Quarkus integration. See https://github.com/quarkusio/quarkus/issues/47462.

add operations for obtaining the current sessions from the context

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/delegation/MutinyStatelessSessionDelegator.java

The code was not compiling
```
delegate().upsert(entityName, entity);
```
has been removed so I think the aim was to get rid of this method.

Remove MutinyStatelessSessionDelegator#upsert(String entityName, Object entity) method

---

ci/snapshot-publish.Jenkinsfile
jreleaser.yml
publish.gradle

Since JReleaser won't work with snapshot publishing to nexus3 and from the docs it's suggested to just use a regular publish plugin: https://central.sonatype.org/publish/publish-portal-snapshots/#publishing-via-other-methods
- https://github.com/hibernate/hibernate-orm/commit/f9164f289f2af6f0992b196d1b4799cfe5b27d28
- https://github.com/hibernate/hibernate-orm/commit/b58564dce380f62eee5e2dc618b0aa9fed6e4235

Adjust snapshot publishing to use the publish plugin instead of JReleaser

---

gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/ReactiveMutationQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/ReactiveNativeQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/ReactiveQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/ReactiveQueryImplementor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/ReactiveSelectionQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sql/internal/ReactiveNativeQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sql/spi/ReactiveNativeQueryImplementor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/ReactiveSqmSelectionQuery.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ReactiveQuerySqmImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ReactiveSqmSelectionQueryImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveSqmQueryImplementor.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java

adapt to changes to setParameter() signature
Fix #2251

Upgrade Hibernate ORM to to 7.0.0.CR2

---

README.md
gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/mutation/ReactiveUpdateCoordinatorStandard.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/TimestampTest.java

Backport fix for #2138 (pr #2172) to 2.4

[2.4]  Use UPDATE event type for generator where applicable

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java

The method getResultType doesn't return Void.class anymore.
See https://hibernate.atlassian.net/browse/HHH-19386
Fix #2227

Remove workaround for HHH-19386

---

README.md
gradle.properties
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveAbstractMultiIdEntityLoader.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveMultiIdEntityLoaderArrayParam.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveMultiIdEntityLoaderStandard.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/JoinedSubclassInheritanceTest.java

Upgrade Hibernate ORM to 7.0.0.Final

---

build.gradle
hibernate-reactive-core/build.gradle
integration-tests/bytecode-enhancements-it/build.gradle
integration-tests/hibernate-validator-postgres-it/build.gradle
integration-tests/techempower-postgres-it/build.gradle
integration-tests/verticle-postgres-it/build.gradle
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

- Upgrade JBoss Logging Annotations and Processor to 3.0.4
- Upgrade MySQL JDBC driver to 9.3.0
- Upgrade MariaDB JDBC driver to 3.5.3
- Upgrade MSSQL JDBC driver to 12.10.0.jre11
- Upgrade PostgresSQL JDBC driver to 42.7.5
- Upgrade AssertJ to 3.27.3
- Upgrade Testcontainers to 1.21.0

Dependencies upgrades: JBoss Logging, jdbc drivers, AssertJ, and Testcontainers 

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java
integration-tests/hibernate-validator-postgres-it/src/test/java/org/hibernate/reactive/it/quarkus/qe/database/BaseReactiveIT.java
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/VertxServer.java
podman.md
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

* Upgrade PostgreSQL to 17.5 (from 17.4)
* Upgrade CockroachDB to v24.3.13 (from v24.1.15)

Upgrade database images for testing

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/CockroachDBDatabase.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/PostgreSQLDatabase.java
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java
integration-tests/hibernate-validator-postgres-it/src/test/java/org/hibernate/reactive/it/quarkus/qe/database/BaseReactiveIT.java
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/VertxServer.java
podman.md
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Backport #2263 for 2.4 branch
- Upgrade PostgreSQL to 17.5 (from 17.4)
- Upgrade CockroachDB to v24.3.13 (from v24.1.15)

[2.4] Upgrade database dependencies for testing

---

README.md
build.gradle
documentation/src/main/asciidoc/reference/introduction.adoc
examples/native-sql-example/build.gradle
examples/session-example/build.gradle
gradle.properties
hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/main/java/org/hibernate/reactive/context/impl/VertxContext.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/TenantDependentPool.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/schema/SchemaValidationTest.java
integration-tests/bytecode-enhancements-it/build.gradle
integration-tests/bytecode-enhancements-it/src/test/java/org/hibernate/reactive/it/BaseReactiveIT.java
integration-tests/hibernate-validator-postgres-it/build.gradle
integration-tests/hibernate-validator-postgres-it/src/test/java/org/hibernate/reactive/it/quarkus/qe/database/BaseReactiveIT.java
integration-tests/techempower-postgres-it/build.gradle
integration-tests/techempower-postgres-it/src/main/java/org/hibernate/reactive/it/techempower/WorldVerticle.java
integration-tests/techempower-postgres-it/src/test/java/org/hibernate/reactive/techempower/TechEmpowerTest.java
integration-tests/verticle-postgres-it/build.gradle
integration-tests/verticle-postgres-it/src/main/java/org/hibernate/reactive/it/verticle/ProductVerticle.java
integration-tests/verticle-postgres-it/src/test/java/org/hibernate/reactive/it/LocalContextTest.java
tooling/jbang/CockroachDBReactiveTest.java.qute
tooling/jbang/Db2ReactiveTest.java.qute
tooling/jbang/Example.java
tooling/jbang/MariaDBReactiveTest.java.qute
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/PostgreSQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Fix #2036 
First draft to have an idea of how the API have changed.
It needs to be  cleaned up.

Upgrade Vert.x SQL client to 5

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLQueryTest.java

Backport https://github.com/hibernate/hibernate-reactive/issues/1793 (PR https://github.com/hibernate/hibernate-reactive/pull/2281) to `3.0`

[3.0]  Test HQL new operator with many-to-one

---

AUTHORS.txt
CONTRIBUTING.md

see https://github.com/hibernate/hibernate-orm/pull/10266

Add AUTHORS.txt

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcConnectionProvider.java

Fix #2186
@yrodiere, is this better?
@dreab8, You are workging on https://github.com/hibernate/hibernate-reactive/issues/2154, right? Do you have a test case I can borrow to see the error? Thanks
The new error message:
```
The application requested a JDBC connection, but Hibernate Reactive doesn't use JDBC.
This could be caused by a bug or the use of an unsupported feature in Hibernate Reactive
```

Improve error message when asking for a JDBC connection

---

README.md
gradle.properties

Backport #2300 (PR https://github.com/hibernate/hibernate-reactive/pull/2301) to the 3.0 branch

[3.0] Upgrade Hibernate ORM to 7.0.2.Final

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/ReactiveIdentifierGenerator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/ReactiveCompositeNestedGeneratedValueGenerator.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/tuple/entity/ReactiveEntityMetamodel.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CompositeIdWithGeneratedValuesTest.java

Fix #2154 
Rebased #2296 after the upgrade to ORM 7.0.2.Final (that includes https://github.com/hibernate/hibernate-orm/pull/10301)
I squashed together the commits related to the fix, added some assertions to the test, and applied some refactoring

 Composite key with generated value not working properly

---

.github/workflows/build.yml

Backport #2309 (PR https://github.com/hibernate/hibernate-reactive/pull/2310) for 3.0

[3.0] Add JDK 26-ea to the build

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/internal/ReactiveDeferredResultSetAccess.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java

Backport #2314 (https://github.com/hibernate/hibernate-reactive/pull/2315) for 2.4

[2.4] Syntax error when using setMaxResults() on native queries with SQL Server / PostgreSQL

---

build.gradle
examples/native-sql-example/build.gradle
examples/session-example/build.gradle

since now our snapshots are published to central.
I'm not sure if these were used in some builds or not as I couldn't find the property anywhere else in the project (it seems)

Update optional snapshot repositories to point to central snapshots instead of ossrh ones

---

examples/native-sql-example/build.gradle
examples/session-example/build.gradle
gradle.properties
hibernate-reactive-core/build.gradle

Backport #2333 (PR #2334) to 3.0

[3.0] Rename property for enabling snapshot repositories

---

examples/native-sql-example/build.gradle
examples/session-example/build.gradle
gradle.properties
hibernate-reactive-core/build.gradle

Fix #2333 
It also adds a commit to print the resolved Hibernate ORM and Vert.x versions. Useful when building with snapshots and the version is specified using ranges.

Rename snapshot repo property

---

build.gradle
documentation/build.gradle
examples/native-sql-example/build.gradle
examples/session-example/build.gradle
gradle.properties
gradle/libs.versions.toml
hibernate-reactive-core/build.gradle
integration-tests/bytecode-enhancements-it/build.gradle
integration-tests/hibernate-validator-postgres-it/build.gradle
integration-tests/techempower-postgres-it/build.gradle
integration-tests/verticle-postgres-it/build.gradle
local-build-plugins/src/main/java/org/hibernate/reactive/env/VersionsPlugin.java
local-build-plugins/src/main/java/org/hibernate/reactive/env/VersionsTomlParser.java
settings.gradle

Follows https://github.com/hibernate/hibernate-reactive/pull/2331
Fix #1989  
@exoego, I reverted the checks you have removed and made a few changes. Now we have the versions in the catalog but we also have the same behaviour as before.
I've also fixed a few mistakes I found along the way. I will apply these changes to other branches and make sure that everything still works.

Migrate to Gradle version catalogs

---

build.gradle
documentation/build.gradle
examples/native-sql-example/build.gradle
examples/session-example/build.gradle
gradle.properties
gradle/libs.versions.toml
hibernate-reactive-core/build.gradle
integration-tests/bytecode-enhancements-it/build.gradle
integration-tests/hibernate-validator-postgres-it/build.gradle
integration-tests/techempower-postgres-it/build.gradle
integration-tests/verticle-postgres-it/build.gradle
local-build-plugins/src/main/java/org/hibernate/reactive/env/VersionsPlugin.java
local-build-plugins/src/main/java/org/hibernate/reactive/env/VersionsTomlParser.java
settings.gradle

Backport #1989 (PR #2331) to 2.4
Plus, some test dependencies upgrade:
* AssertJ from 3.26.7 to 3.27.7
* Testcontainers from 1.20.6 to 1.21.0
* PostgreSQL from 42.7.4 to 42.7.5
* MariaDB JDBC Driver from 3.5.1 to 3.5.3
* MSSQL JDBC Driver from 12.8.1.jre11 to 12.10.0.jre11
* MySQL JDBC Driver from 9.1.0 to 9.3.0

[2.4] Migrate to Gradle version catalogs

---

.github/dependabot.yml

Backport #1136 (PR https://github.com/hibernate/hibernate-reactive/pull/2344) to 3.0

[3.0] Update dependabot configuration ci 

---

.github/dependabot.yml

Backport #1136 (PR https://github.com/hibernate/hibernate-reactive/pull/2344) to 2.4

[2.4] Update dependabot configuration

---

gradle/libs.versions.toml
hibernate-reactive-core/build.gradle

Supersedes https://github.com/hibernate/hibernate-reactive/pull/2357
Requires extra dependency org.junit.platform:junit-platform-launcher:1.13.3
---
updated-dependencies:
- dependency-name: org.junit.jupiter:junit-jupiter-api dependency-version: 5.13.3 dependency-type: direct:production update-type: version-update:semver-minor
- dependency-name: org.junit.jupiter:junit-jupiter-engine dependency-version: 5.13.3 dependency-type: direct:production update-type: version-update:semver-minor ...

Bump junitVersion from 5.11.3 to 5.13.3

---

build.gradle
ci/snapshot-publish.Jenkinsfile
gradle/libs.versions.toml

Fix #2368 
We don't use it anymore since the switch to JRelease. This was just a left over.

Remove gradle-nexus:publish-plugin from the catalog

---

.github/workflows/build.yml
hibernate-reactive-core/src/test/java/org/hibernate/reactive/containers/MySQLDatabase.java
tooling/docker/mysql.Dockerfile
tooling/jbang/MySQLReactiveTest.java.qute
tooling/jbang/ReactiveTest.java

Backport https://github.com/hibernate/hibernate-reactive/issues/2270 (PR https://github.com/hibernate/hibernate-reactive/pull/2365) to 2.4

[2.4] Upgrade MySQL docker image to container-registry.oracle.com/mysql/community-server:9.3.0 dependencies

---

build.gradle
ci/snapshot-publish.Jenkinsfile
gradle/libs.versions.toml

Backport https://github.com/hibernate/hibernate-reactive/issues/2368 (PR https://github.com/hibernate/hibernate-reactive/pull/2367) to 2.4

[2.4] Remove gradle-nexus:publish-plugin from the catalog

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/results/graph/embeddable/internal/ReactiveEmbeddableInitializerImpl.java

Backport #2381 (PR #2382) for 3.0

[3.0] Fix chaining in ReactiveEmbeddableInitializerImpl#reactiveResolveInstance

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveAbstractPersisterDelegate.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveJoinedSubclassEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveSingleTableEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/entity/impl/ReactiveUnionSubclassEntityPersister.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/query/sqm/internal/ConcreteSqmSelectReactiveQueryPlan.java

Align some codes that changed in ORM 7.1.0.CR2.

Extra  changes for ORM 7.1.0.CR2

---

README.md

For Hibernate ORM and Vert.x.
The current automated release system and dependabot don't update the readme. It would get out of date at every minor release.
I've included a link to the exact version in the catalog, though.

[3.1] Keep only major.minor version in README

---

README.md

For Hibernate ORM and Vert.x.
The current automated release system and dependabot don't update the readme. It would get out of date at every minor release.
I've included a link to the exact version in the catalog, though.

[4.0] Keep only major.minor version in README

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/JoinedSubclassInheritanceTest.java

Extra commit for #2398 
Better link to the Hibernate Reactive issue, instead of the Vert.x one.

Update reason for disabling the test and formattation

---

gradle/libs.versions.toml
hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveLoaderHelper.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/internal/ReactiveCacheLoadHelper.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/LockOnLoadTest.java

Backport #2332 (PR #https://github.com/hibernate/hibernate-reactive/pull/2371)

[4.0] "Not using JDBC" when locking previously loaded entities in Hibernate Reactive 3

---

.github/dependabot.yml

At the moment, dependabot doesn't support YAML aliased and anchors. So, we need to duplicate the configuration if we want to target multiple branches.

Enable dependabot on 3.1

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/CollectionStatelessSessionListenerTest.java

Fix #2330 
And I removed some warnings in BaseReactiveTest.

[4.1] Test collection events with StatelessSession

---

hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JsonTypeTest.java

Closes #2012 
The issue was fixed when we removed parameters processing (via #2465). We just need to add the test case.
Now it's possible to escape the `?` in native queries with `\\?` (instead of `\\\\\\?`).

[4.1] Test '?' operator for PostgreSQL

---

hibernate-reactive-core/build.gradle
hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JsonTypeTest.java

Backport #2012 (PR #2469)
The issue was fixed when we removed parameters processing (via https://github.com/hibernate/hibernate-reactive/pull/2468). We just need to add the test case.
Now it's possible to escape the `?` in native queries with `\\?` (instead of `\\\\\\?`).

[3.1] Test '?' operator for PostgreSQL 

---

ci/release/Jenkinsfile

Main is on `4.1`  and we have already released `4.1.0.Final`.
~~We will create a new branch when we upgrade to ORM 4.2~~
I changed my mind, I will create a new branch now, so that we can merge PR in `main` when needed

Enable scheduled releases for 4.1

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java
hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongJdbcUrlSchemeTest.java

Terrible error reporting when JDBC scheme is not recognized #2478

---

.github/workflows/build.yml

Backport #2516 (PR #2517) for `4.1`

[4.1] Use GA version of JDK 25 in the build

---

.github/workflows/build.yml

Backport #2516 (PR https://github.com/hibernate/hibernate-reactive/pull/2540) to `3.1`

[3.1] Use GA version of JDK 25 in the build 

---

hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/BatchingConnection.java

Fix #2535
I think that this is the reason of some NullPoitnerException errors experienced by users, but I couldn't create a reproducer so far

[4.2] Fix operations order in BatchingConnection

---

ci/release/Jenkinsfile
release/build.gradle

[4.2] Migrate to release scripts for documentation publishing

---

hibernate-reactive-core/src/test/java/org/hibernate/reactive/EmbeddedIdTest.java

The test shows https://hibernate.atlassian.net/browse/HHH-19792 fixes #2515

[#2515] Add test for Wrong query generated when an EnbeddedId is used in a WHERE clause using the IN operator
